package com.mycompany.myfarm.frontend.paneles;

import com.mycompany.myfarm.backend.MotorJuego;
import com.mycompany.myfarm.backend.creadores.CreadorDeProductos;
import com.mycompany.myfarm.backend.producto.Producto;
import com.mycompany.myfarm.frontend.FramePrograma;
import com.mycompany.myfarm.frontend.dialogs.AccionExitosaDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author ronaldo
 */
public class PanelCreadorDeProductosAnimal extends javax.swing.JPanel {
    private CreadorDeProductos creadorDeProductos;
    /**
     * Creates new form PanelCreadorDeProductos
     */
    public PanelCreadorDeProductosAnimal(CreadorDeProductos creadorDeProductos) {
        initComponents();
        this.creadorDeProductos = creadorDeProductos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblPrecioProducto = new javax.swing.JLabel();
        spnPrecioDeVenta = new javax.swing.JSpinner();
        lblProductoDestace = new javax.swing.JLabel();
        cmbDestace = new javax.swing.JComboBox<>();
        btnCrear = new javax.swing.JButton();
        lblPrecioProducto2 = new javax.swing.JLabel();
        cmbTipoDeProducto = new javax.swing.JComboBox<>();
        btnRegresar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        lblTitulo.setBackground(new java.awt.Color(0, 153, 153));
        lblTitulo.setFont(new java.awt.Font("Ubuntu Sans", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Creador de Productos");
        lblTitulo.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblNombre.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Ingresa el nombre del Producto:");

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));

        lblPrecioProducto.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        lblPrecioProducto.setForeground(new java.awt.Color(0, 0, 0));
        lblPrecioProducto.setText("Precio de venta del producto:");

        spnPrecioDeVenta.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        lblProductoDestace.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        lblProductoDestace.setForeground(new java.awt.Color(0, 0, 0));
        lblProductoDestace.setText("El Producto se obtiene con destace?");

        cmbDestace.setBackground(new java.awt.Color(255, 255, 255));
        cmbDestace.setMaximumRowCount(2);
        cmbDestace.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        cmbDestace.setSelectedIndex(-1);

        btnCrear.setBackground(new java.awt.Color(0, 204, 204));
        btnCrear.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(0, 0, 0));
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        lblPrecioProducto2.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        lblPrecioProducto2.setForeground(new java.awt.Color(0, 0, 0));
        lblPrecioProducto2.setText("Ingresa el tipo de producto que será:");

        cmbTipoDeProducto.setBackground(new java.awt.Color(255, 255, 255));
        cmbTipoDeProducto.setMaximumRowCount(2);
        cmbTipoDeProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimento", "Materia Prima" }));
        cmbTipoDeProducto.setSelectedIndex(-1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPrecioProducto2)
                    .addComponent(lblProductoDestace)
                    .addComponent(lblNombre)
                    .addComponent(lblPrecioProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombre)
                        .addComponent(spnPrecioDeVenta)
                        .addComponent(cmbDestace, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbTipoDeProducto, 0, 173, Short.MAX_VALUE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnPrecioDeVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblProductoDestace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbDestace, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioProducto2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(cmbTipoDeProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        btnRegresar.setBackground(new java.awt.Color(255, 51, 51));
        btnRegresar.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FramePrograma.ponerPanelEnFramePrincipal(new PanelMenuJuego());
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        
        String nombre = obtenerNombre();
        int precioDeVenta = (Integer) spnPrecioDeVenta.getValue();
        boolean seObtieneConDestace = esConDestace();
        int tipoDeAlimento = obtenerTipoDeAlimentoSeleccionado();
        if (nombre != null && tipoDeAlimento != -1) {
            Producto productoNuevo = creadorDeProductos.crearUnNuevoProductoAnimal(nombre, precioDeVenta, seObtieneConDestace, tipoDeAlimento);
            MotorJuego.getAlmacenador().getProductosDisponibles().agregarElemento(productoNuevo);
            AccionExitosaDialog dialog = new AccionExitosaDialog("Producto de animal creado correctamente");
            dialog.setVisible(true);
            limpiarCampos();
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private String obtenerNombre() {
        String nombre = txtNombre.getText();
        if (!nombre.equals("")) {
            boolean elNombreEstaDisponible = creadorDeProductos.elNombreEstaDisponible(nombre);
            if (elNombreEstaDisponible) {
                return nombre;
            } else {
                JOptionPane.showMessageDialog(this, "El nombre del producto que pusiste ya existe elige otro", "Ya existe ese nombre", JOptionPane.ERROR_MESSAGE);
                txtNombre.setText("");
                return null;
            }
        }
        JOptionPane.showMessageDialog(this, "Debes ingresar un nombre para el producto", "Falta Nombre", JOptionPane.ERROR_MESSAGE);
        return null;
    }
    
    private void limpiarCampos(){
        txtNombre.setText("");
        spnPrecioDeVenta.setValue(0);
        cmbDestace.setSelectedIndex(-1);
        cmbTipoDeProducto.setSelectedIndex(-1);
    }
    
    private boolean esConDestace() {
        try {
            String texto = (String) cmbDestace.getSelectedItem();
            return texto.equals("Sí");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar si es con destace", "Error", JOptionPane.ERROR_MESSAGE);            
        }
        return false;
    }
    
    private int obtenerTipoDeAlimentoSeleccionado() {  
        try {
            String tipoDePlanta = (String) cmbTipoDeProducto.getSelectedItem();
            if (tipoDePlanta.equals("Alimento")) {
                return 1;
            } else if (tipoDePlanta.equals("Materia Prima")) {
                return 2;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar el tipo de alimento", "Falta dato", JOptionPane.ERROR_MESSAGE);
        }
        return -1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbDestace;
    private javax.swing.JComboBox<String> cmbTipoDeProducto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecioProducto;
    private javax.swing.JLabel lblPrecioProducto2;
    private javax.swing.JLabel lblProductoDestace;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JSpinner spnPrecioDeVenta;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
