/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.myfarm.frontend.paneles;
import com.mycompany.myfarm.backend.MotorJuego;
import com.mycompany.myfarm.backend.creadores.CreadorDePlantas;
import com.mycompany.myfarm.backend.planta.Planta;
import com.mycompany.myfarm.backend.semilla.Semilla;
import com.mycompany.myfarm.frontend.FramePrograma;
import com.mycompany.myfarm.frontend.dialogs.AccionExitosaDialog;
import com.mycompany.myfarm.frontend.dialogs.SeleccionProductosPlantaDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ronaldo
 */
public class PanelCreacionDePlantas extends javax.swing.JPanel {
    private CreadorDePlantas creador;
    /**
     * Creates new form PanelCreacionDePlantas
     */
    public PanelCreacionDePlantas(CreadorDePlantas creador) {
        initComponents();
        this.creador=creador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblPrecio = new javax.swing.JLabel();
        spnCantidadSemillas = new javax.swing.JSpinner();
        lblCantidadSemillas = new javax.swing.JLabel();
        spnPrecioCompraSemilla = new javax.swing.JSpinner();
        cmbTipoDePlanta = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnCrearPlanta = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(0, 204, 153));
        jLabel1.setFont(new java.awt.Font("Ubuntu Sans", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Creador de Plantas");
        jLabel1.setOpaque(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setOpaque(false);

        lblPrecio.setFont(new java.awt.Font("Ubuntu Sans", 1, 24)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(0, 0, 0));
        lblPrecio.setText("Precio de compra de una semilla en el mercado:");

        spnCantidadSemillas.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        lblCantidadSemillas.setFont(new java.awt.Font("Ubuntu Sans", 1, 24)); // NOI18N
        lblCantidadSemillas.setForeground(new java.awt.Color(0, 0, 0));
        lblCantidadSemillas.setText("Cantidad de semillas para sembrar:");

        spnPrecioCompraSemilla.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        cmbTipoDePlanta.setMaximumRowCount(2);
        cmbTipoDePlanta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Planta Grano", "Planta Fruta" }));
        cmbTipoDePlanta.setSelectedIndex(-1);
        cmbTipoDePlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoDePlantaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tipo de planta:");

        lblNombre1.setFont(new java.awt.Font("Ubuntu Sans", 1, 24)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre1.setText("Ingresa el nombre de la planta:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(122, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPrecio)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnPrecioCompraSemilla)
                            .addComponent(cmbTipoDePlanta, 0, 175, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(271, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCantidadSemillas)
                            .addComponent(lblNombre1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnCantidadSemillas, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnCantidadSemillas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidadSemillas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spnPrecioCompraSemilla, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoDePlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        btnRegresar.setBackground(new java.awt.Color(255, 51, 51));
        btnRegresar.setFont(new java.awt.Font("Ubuntu Sans", 1, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnCrearPlanta.setBackground(new java.awt.Color(0, 204, 51));
        btnCrearPlanta.setFont(new java.awt.Font("Ubuntu Sans", 1, 24)); // NOI18N
        btnCrearPlanta.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearPlanta.setText("Crear Planta");
        btnCrearPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPlantaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(417, 417, 417)
                        .addComponent(btnCrearPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoDePlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoDePlantaActionPerformed
        
    }//GEN-LAST:event_cmbTipoDePlantaActionPerformed

    private void btnCrearPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPlantaActionPerformed
        String nombreDeLaPlanta = obtenerTexto(txtNombre);
        int cantidadDeSemillas = (Integer) spnCantidadSemillas.getValue();
        int precioCompraSemillaMercado = (Integer) spnPrecioCompraSemilla.getValue();
        int tipoPlanta = evaluarTipoDePlanta();
        
        if (nombreDeLaPlanta!=null  && tipoPlanta != -1) {
            Planta planta = creador.crearUnaPlanta(nombreDeLaPlanta, cantidadDeSemillas, tipoPlanta);
            Semilla semilla = new Semilla(planta, nombreDeLaPlanta, precioCompraSemillaMercado);
            MotorJuego.getAlmacenador().getMercadoGeneral().getSemillasDisponibles().agregarElemento(semilla);
            SeleccionProductosPlantaDialog dialgo= new SeleccionProductosPlantaDialog(tipoPlanta);
            dialgo.setVisible(true);
            AccionExitosaDialog dialog = new AccionExitosaDialog("Planta creada Correctamente");
            dialog.setVisible(true);
            limpiarCampos();
        }
    }//GEN-LAST:event_btnCrearPlantaActionPerformed
    
    public String obtenerTexto(JTextField txtTexto){
        String nombreDeLaPlanta = txtTexto.getText();
        if(!nombreDeLaPlanta.equals("")){
            return nombreDeLaPlanta;
        }
        JOptionPane.showMessageDialog(this,"Debes ingresar un nombre para la planta","Falta dato",JOptionPane.ERROR_MESSAGE);
        return null;
    }
    
    public void limpiarCampos(){
        txtNombre.setText("");
        spnCantidadSemillas.setValue(1);
        spnPrecioCompraSemilla.setValue(0);
        cmbTipoDePlanta.setSelectedItem(null);
    }
    
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FramePrograma.ponerPanelEnFramePrincipal(new PanelMenuJuego());
    }//GEN-LAST:event_btnRegresarActionPerformed
    //metodo que se encarga de verificar que tipo de planta selecciono para crear el jugador 
    public int evaluarTipoDePlanta() {
        String tipoDePlanta = (String) cmbTipoDePlanta.getSelectedItem();
        try {
            if (tipoDePlanta.equals("Planta Grano")) {
                return 1;
            } else if (tipoDePlanta.equals("Planta Fruta")) {
                return 2;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Selecciona el tipo de planta", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return -1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearPlanta;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbTipoDePlanta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCantidadSemillas;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JSpinner spnCantidadSemillas;
    private javax.swing.JSpinner spnPrecioCompraSemilla;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
