/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.myfarm.frontend.paneles;

import com.mycompany.myfarm.backend.MotorJuego;
import com.mycompany.myfarm.backend.creadores.CreadorDeProductos;
import com.mycompany.myfarm.backend.producto.Producto;
import com.mycompany.myfarm.frontend.FramePrograma;
import com.mycompany.myfarm.frontend.dialogs.AccionExitosaDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author ronaldo
 */
public class PanelCreacionProductoPlanta extends javax.swing.JPanel {
    private CreadorDeProductos creador;
    /**
     * Creates new form PanelCreacionProductoPlanta
     */
    public PanelCreacionProductoPlanta(CreadorDeProductos creador) {
        initComponents();
        inicializarComboPrecioDeVenta();
        this.creador=creador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEncabezado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cmbPrecioDeVenta = new javax.swing.JComboBox<>();
        cmbTipoDeAlimento = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnCrearAlimento = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        lblEncabezado.setBackground(new java.awt.Color(102, 204, 0));
        lblEncabezado.setFont(new java.awt.Font("Ubuntu Mono", 1, 48)); // NOI18N
        lblEncabezado.setForeground(new java.awt.Color(0, 0, 0));
        lblEncabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEncabezado.setText("Creacion de alimento planta");
        lblEncabezado.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        lblNombre.setFont(new java.awt.Font("Ubuntu Mono", 1, 19)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Ingresa el precio de venta del alimento en el mercado:");

        lblNombre1.setFont(new java.awt.Font("Ubuntu Mono", 1, 19)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre1.setText("Ingresa el nombre del alimento :");

        lblNombre2.setFont(new java.awt.Font("Ubuntu Mono", 1, 19)); // NOI18N
        lblNombre2.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre2.setText("Selecciona el tipo del alimento:");

        cmbTipoDeAlimento.setMaximumRowCount(2);
        cmbTipoDeAlimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grano", "Fruto" }));
        cmbTipoDeAlimento.setSelectedIndex(-1);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Debes configurar todos los campos para poder crear un producto");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombre2)
                    .addComponent(lblNombre1)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre)
                    .addComponent(cmbPrecioDeVenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbTipoDeAlimento, 0, 182, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(145, 145, 145))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbPrecioDeVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombre2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbTipoDeAlimento, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnCrearAlimento.setText("Crear Alimento");
        btnCrearAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearAlimentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(390, 390, 390)
                        .addComponent(btnCrearAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearAlimentoActionPerformed
        String nombre =obtenerNombre();
        int precioDeVenta =cmbPrecioDeVenta.getSelectedIndex()+1;
        int tipoDeAlimento = evaluarTipoDeAlimento();
        if(nombre!=null && tipoDeAlimento!=-1){
            boolean nombreDisponible=creador.elNombreEstaDisponible(nombre);
            if(nombreDisponible){
                Producto nuevoProducto = creador.crearUnNuevoProductoPlanta(nombre, precioDeVenta, tipoDeAlimento);
                MotorJuego.getAlmacenador().getProductosDisponibles().agregarElemento(nuevoProducto);
                limpiarCampos();
                AccionExitosaDialog dialog = new AccionExitosaDialog("Alimento creado correctamente");
                dialog.setVisible(true);
            }
        }
       
    }//GEN-LAST:event_btnCrearAlimentoActionPerformed

    private void limpiarCampos(){
        txtNombre.setText("");
    }
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FramePrograma.ponerPanelEnFramePrincipal(new PanelMenuJuego());
    }//GEN-LAST:event_btnRegresarActionPerformed

    private String obtenerNombre() {
        String nombre = txtNombre.getText();
        if (!nombre.equals("")) {
            return nombre;
        }
        JOptionPane.showMessageDialog(this, "Debes ingresar un nombre para el alimento", "Falta nombre", JOptionPane.ERROR_MESSAGE);
        return null;
    }
    
    private int evaluarTipoDeAlimento(){
        int tipoDeAlimento=cmbTipoDeAlimento.getSelectedIndex();
        if(tipoDeAlimento==-1){
            JOptionPane.showMessageDialog(this,"Debes seleccionar el tipo de Alimento","Falta tipo de alimento",JOptionPane.ERROR_MESSAGE);
        }
        return tipoDeAlimento;
    }

    
    private void inicializarComboPrecioDeVenta(){
        for(int i=1; i<=200; i++){
            cmbPrecioDeVenta.addItem(""+i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearAlimento;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbPrecioDeVenta;
    private javax.swing.JComboBox<String> cmbTipoDeAlimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEncabezado;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
