/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.myfarm.frontend.paneles;


import com.mycompany.myfarm.backend.creadores.CreadorDeAnimales;
import com.mycompany.myfarm.backend.creadores.CreadorDePlantas;
import com.mycompany.myfarm.frontend.FramePrograma;
import com.mycompany.myfarm.frontend.dialogs.TipoDeProductoDialog;
import com.mycompany.myfarm.frontend.dialogs.partida.MenuInicioPartidaDialog;

/**
 *
 * @author ronaldo
 */
public class PanelMenuJuego extends javax.swing.JPanel {
  
    /**
     * Creates new form PanelMenuJuego
     */
    public PanelMenuJuego() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        pnlBotones = new javax.swing.JPanel();
        btnCrearPlanta = new javax.swing.JButton();
        btnIniciarPartida = new javax.swing.JButton();
        btnCrearAnimal = new javax.swing.JButton();
        btnCrearProducto = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        lblTitulo.setBackground(new java.awt.Color(255, 153, 0));
        lblTitulo.setFont(new java.awt.Font("Ubuntu Sans", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Menu Juego My Farm");
        lblTitulo.setMaximumSize(new java.awt.Dimension(487, 63));
        lblTitulo.setMinimumSize(new java.awt.Dimension(487, 63));
        lblTitulo.setOpaque(true);

        btnRegresar.setBackground(new java.awt.Color(51, 255, 204));
        btnRegresar.setFont(new java.awt.Font("Ubuntu Mono", 1, 19)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("Regresar a Menu Principal");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        pnlBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlBotones.setOpaque(false);

        btnCrearPlanta.setBackground(new java.awt.Color(153, 204, 255));
        btnCrearPlanta.setFont(new java.awt.Font("Ubuntu Mono", 1, 19)); // NOI18N
        btnCrearPlanta.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearPlanta.setText("CrearPlanta");
        btnCrearPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPlantaActionPerformed(evt);
            }
        });

        btnIniciarPartida.setBackground(new java.awt.Color(153, 204, 255));
        btnIniciarPartida.setFont(new java.awt.Font("Ubuntu Mono", 1, 19)); // NOI18N
        btnIniciarPartida.setForeground(new java.awt.Color(0, 0, 0));
        btnIniciarPartida.setText("Iniciar Partida");
        btnIniciarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarPartidaActionPerformed(evt);
            }
        });

        btnCrearAnimal.setBackground(new java.awt.Color(153, 204, 255));
        btnCrearAnimal.setFont(new java.awt.Font("Ubuntu Mono", 1, 19)); // NOI18N
        btnCrearAnimal.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearAnimal.setText("CrearAnimal");
        btnCrearAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearAnimalActionPerformed(evt);
            }
        });

        btnCrearProducto.setBackground(new java.awt.Color(153, 204, 255));
        btnCrearProducto.setFont(new java.awt.Font("Ubuntu Mono", 1, 19)); // NOI18N
        btnCrearProducto.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearProducto.setText("Crear Producto");
        btnCrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnIniciarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnCrearPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnCrearAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnCrearProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(268, 268, 268))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearAnimalActionPerformed
        CreadorDeAnimales creadorDeAnimales = new CreadorDeAnimales();
        creadorDeAnimales.iniciarCreacion();
    }//GEN-LAST:event_btnCrearAnimalActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FramePrograma.ponerPanelEnFramePrincipal(new PanelMenuPrincipal());
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCrearPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPlantaActionPerformed
        CreadorDePlantas creador = new CreadorDePlantas();
        creador.iniciarCreacion();
    }//GEN-LAST:event_btnCrearPlantaActionPerformed

    private void btnIniciarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarPartidaActionPerformed
        MenuInicioPartidaDialog dialog = new MenuInicioPartidaDialog();
        dialog.setVisible(true);
    }//GEN-LAST:event_btnIniciarPartidaActionPerformed

    private void btnCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProductoActionPerformed
        
        TipoDeProductoDialog dialog = new TipoDeProductoDialog();
        dialog.setVisible(true);
    }//GEN-LAST:event_btnCrearProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearAnimal;
    private javax.swing.JButton btnCrearPlanta;
    private javax.swing.JButton btnCrearProducto;
    private javax.swing.JButton btnIniciarPartida;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBotones;
    // End of variables declaration//GEN-END:variables
}
