/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.myfarm.frontend.paneles;

import com.mycompany.myfarm.backend.MotorJuego;
import com.mycompany.myfarm.backend.ResumenAnimal;
import com.mycompany.myfarm.backend.ResumenPartida;
import com.mycompany.myfarm.backend.ResumenPlanta;
import com.mycompany.myfarm.backend.listaEnlazada.ListaEnlazadaGenerica;
import com.mycompany.myfarm.frontend.FramePrograma;
import com.mycompany.myfarm.frontend.dialogs.ExportarReporteDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ronaldo
 */
public class PanelReportes extends javax.swing.JPanel {
    private ListaEnlazadaGenerica<ResumenPartida> partidas;
    private ListaEnlazadaGenerica<ResumenAnimal> animales;
    private ListaEnlazadaGenerica<ResumenPlanta> plantas;
    /**
     * Creates new form PanelReportes
     */
    public PanelReportes(ListaEnlazadaGenerica<ResumenPartida> partidas,
            ListaEnlazadaGenerica<ResumenAnimal> animales,
            ListaEnlazadaGenerica<ResumenPlanta> plantas) {
        initComponents();
        this.partidas = partidas;
        this.animales = animales;
        this.plantas=plantas;
        cargarTablaPartidas();
        cargarTablaAnimales();
        cargarTablaPlantas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEncabezado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPartidas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAnimales = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaPlantas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnExportar = new javax.swing.JButton();
        cmbReportes = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));

        lblEncabezado.setBackground(new java.awt.Color(153, 0, 0));
        lblEncabezado.setFont(new java.awt.Font("Ubuntu Mono", 0, 48)); // NOI18N
        lblEncabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEncabezado.setText("REPORTES");
        lblEncabezado.setOpaque(true);

        tablaPartidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Partida", "Duracion", "Alimento Generado", "Alimento Consumido", "Celdas Compradas"
            }
        ));
        jScrollPane1.setViewportView(tablaPartidas);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tablaAnimales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Crias Compradas", "Unidades Destasadas"
            }
        ));
        jScrollPane2.setViewportView(tablaAnimales);

        tablaPlantas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad Adquirida", "Celdas Sembradas"
            }
        ));
        jScrollPane3.setViewportView(tablaPlantas);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("REPORTE PARTIDAS");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("REPORTE ANIMALES");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("REPORTE PLANTAS");

        btnExportar.setText("EXPORTAR");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        cmbReportes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Partidas", "Animales", "Plantas" }));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Selecciona el archivo a exportar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))))
            .addGroup(layout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(398, 398, 398))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(390, 390, 390))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FramePrograma.ponerPanelEnFramePrincipal(new PanelMenuPrincipal());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        ExportarReporteDialog dialog =new ExportarReporteDialog(MotorJuego.getAlmacenador().getReporte(), cmbReportes.getSelectedIndex());
        dialog.setVisible(true);
        
    }//GEN-LAST:event_btnExportarActionPerformed

    public void cargarTablaPartidas(){
        DefaultTableModel modelo = (DefaultTableModel) tablaPartidas.getModel();
        for (int i = 0; i < partidas.getTamaño(); i++) {
            modelo.addRow(new Object[]{partidas.obtenerContenido(i).getNombrePartida(),partidas.obtenerContenido(i).getDuracionPartida()
            ,partidas.obtenerContenido(i).getAlimentosGenerados(),partidas.obtenerContenido(i).getProductosConsumidos(),partidas.obtenerContenido(i).getCantidadDeCeldasCompradas()});
        }
    }
    public void cargarTablaAnimales() {
        DefaultTableModel modelo = (DefaultTableModel) tablaAnimales.getModel();
        for (int i = 0; i < animales.getTamaño(); i++) {
            modelo.addRow(new Object[]{animales.obtenerContenido(i).getNombrePlanta(), animales.obtenerContenido(i).getCantidadCriasVendidas(),
                 animales.obtenerContenido(i).getCantidadUnidadesDestazada()});
        }
    }

    public void cargarTablaPlantas() {
        DefaultTableModel modelo = (DefaultTableModel) tablaPlantas.getModel();
        for (int i = 0; i < plantas.getTamaño(); i++) {
            modelo.addRow(new Object[]{plantas.obtenerContenido(i).getNombre(), 
                plantas.obtenerContenido(i).getTotalSemillasAdquiridas(),
                plantas.obtenerContenido(i).getCeldasSembradas()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JComboBox<String> cmbReportes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblEncabezado;
    private javax.swing.JTable tablaAnimales;
    private javax.swing.JTable tablaPartidas;
    private javax.swing.JTable tablaPlantas;
    // End of variables declaration//GEN-END:variables
}
