/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.myfarm.frontend.paneles;

import com.mycompany.myfarm.backend.MotorJuego;
import com.mycompany.myfarm.backend.animal.Animal;
import com.mycompany.myfarm.backend.creadores.CreadorDeAnimales;
import com.mycompany.myfarm.frontend.FramePrograma;
import com.mycompany.myfarm.frontend.dialogs.AgregarProductosSinDestaceDialog;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author ronaldo
 */
public class PanelCreacionDeAnimal extends javax.swing.JPanel {
    private CreadorDeAnimales creadorDeAnimales;
     /**
     * Creates new form PanelCreacionDeAnimal
     */
    public PanelCreacionDeAnimal(CreadorDeAnimales creadorDeAnimales) {
        initComponents();
        this.creadorDeAnimales=creadorDeAnimales;
        colocarNumerosAComboBox();
        colocarEspaciosParcelaAComboBox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbEdadMaxima = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbDestasable = new javax.swing.JComboBox<>();
        lblTipoDeAnimal = new javax.swing.JLabel();
        cmbTipoDeAnimal = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbPrecioDeCria = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbPrecioCompraEnElMercado = new javax.swing.JComboBox<>();
        txtEspacio = new javax.swing.JLabel();
        cmbEspacioEnParcela = new javax.swing.JComboBox<>();
        btnRegresar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        lblTitulo.setBackground(new java.awt.Color(255, 51, 51));
        lblTitulo.setFont(new java.awt.Font("Ubuntu Mono", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Creador de Animales");
        lblTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.magenta, java.awt.Color.lightGray, java.awt.Color.green, java.awt.Color.gray));
        lblTitulo.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 153));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingresa el nombre del animal:");

        txtNombre.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Edad Maxima del animal:");

        cmbEdadMaxima.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        cmbEdadMaxima.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("El animal es destasable:");

        cmbDestasable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        cmbDestasable.setSelectedIndex(-1);
        cmbDestasable.setPreferredSize(new java.awt.Dimension(95, 42));

        lblTipoDeAnimal.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        lblTipoDeAnimal.setForeground(new java.awt.Color(0, 0, 0));
        lblTipoDeAnimal.setText("Tipo de animal:");

        cmbTipoDeAnimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Onmivoro", "Herbivoro" }));
        cmbTipoDeAnimal.setSelectedIndex(-1);
        cmbTipoDeAnimal.setMinimumSize(new java.awt.Dimension(134, 42));
        cmbTipoDeAnimal.setPreferredSize(new java.awt.Dimension(134, 42));

        jLabel5.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Precio de venta de una cria en el mercado:");

        cmbPrecioDeCria.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        cmbPrecioDeCria.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Precio de compra del animal en el mercado:");

        cmbPrecioCompraEnElMercado.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        cmbPrecioCompraEnElMercado.setToolTipText("");

        txtEspacio.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        txtEspacio.setForeground(new java.awt.Color(0, 0, 0));
        txtEspacio.setText("Espacio del animal en una parcela");

        cmbEspacioEnParcela.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        cmbEspacioEnParcela.setSelectedIndex(-1);
        cmbEspacioEnParcela.setPreferredSize(new java.awt.Dimension(95, 42));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addComponent(cmbEdadMaxima, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbPrecioCompraEnElMercado, 0, 218, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(lblTipoDeAnimal)
                            .addComponent(jLabel5)
                            .addComponent(txtEspacio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbTipoDeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDestasable, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPrecioDeCria, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEspacioEnParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbEdadMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbPrecioCompraEnElMercado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbPrecioDeCria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDestasable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEspacio)
                    .addComponent(cmbEspacioEnParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoDeAnimal)
                    .addComponent(cmbTipoDeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnRegresar.setBackground(new java.awt.Color(204, 51, 0));
        btnRegresar.setFont(new java.awt.Font("Ubuntu Mono", 1, 19)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnAceptar.setBackground(new java.awt.Color(51, 255, 204));
        btnAceptar.setFont(new java.awt.Font("Ubuntu Mono", 1, 19)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(0, 0, 0));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FramePrograma.ponerPanelEnFramePrincipal(new PanelMenuJuego());
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String nombre= obtenerNombre();
        int edadMaxima=cmbEdadMaxima.getSelectedIndex()+1;
        int precioDeCompra = cmbPrecioCompraEnElMercado.getSelectedIndex()+1;
        int precioDeUnaCria=cmbPrecioDeCria.getSelectedIndex()+1;
        boolean esDestasable=esDestasable();
        double espacioEnParcela=obtenerEspacioEnParcela();
        
        if (nombre != null && verificarQueElJugadorSeleccionoUnEstado(cmbDestasable) && verificarQueElJugadorSeleccionoUnEstado(cmbTipoDeAnimal)) {
            Animal animal = creadorDeAnimales.crearAnimal(nombre, edadMaxima, precioDeUnaCria, precioDeCompra, esDestasable,espacioEnParcela, cmbTipoDeAnimal.getSelectedIndex());
            MotorJuego.getAlmacenador().getMercadoGeneral().getAnimalesDisponibles().agregarElemento(animal);
            limpiarTodosLosCampos();
            AgregarProductosSinDestaceDialog dialog = new AgregarProductosSinDestaceDialog(creadorDeAnimales);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    
    public void limpiarTodosLosCampos(){
        txtNombre.setText("");
        cmbTipoDeAnimal.setSelectedIndex(-1);
        cmbDestasable.setSelectedIndex(-1);
    }
    
    private double obtenerEspacioEnParcela() {
        String espacioEnParcelaString = (String) cmbEspacioEnParcela.getSelectedItem();
        double espacioEnParcela = Double.valueOf(espacioEnParcelaString);
        return espacioEnParcela;
    }
    private String obtenerNombre() {
        String nombre = txtNombre.getText();
        if (nombre.equals("")) {
            JOptionPane.showMessageDialog(this, "Debes ingresar un nombre", "Falta nombre", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        return nombre;
    }
    private boolean verificarQueElJugadorSeleccionoUnEstado(JComboBox<String> comboBox){
        if(comboBox.getSelectedIndex()==0 ||comboBox.getSelectedIndex()==1 ){
            return true;
        }
        JOptionPane.showMessageDialog(this,"No seleccionaste el destace O el tipo de animal verifica", "Faltó dato", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    private boolean esDestasable(){
        return cmbDestasable.getSelectedIndex()==0;
    }
    

    private void colocarEspaciosParcelaAComboBox(){
        for(double i=0.5; i<=5; i=i+0.5){
            cmbEspacioEnParcela.addItem(""+i);
        }
    }
    private void colocarNumerosAComboBox() {
        for (int i = 1; i <= 50; i++) {
            if (i <= 20) {
                cmbEdadMaxima.addItem("" + i);
            }
            cmbPrecioDeCria.addItem("" + i);
            cmbPrecioCompraEnElMercado.addItem(""+i);
           
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbDestasable;
    private javax.swing.JComboBox<String> cmbEdadMaxima;
    private javax.swing.JComboBox<String> cmbEspacioEnParcela;
    private javax.swing.JComboBox<String> cmbPrecioCompraEnElMercado;
    private javax.swing.JComboBox<String> cmbPrecioDeCria;
    private javax.swing.JComboBox<String> cmbTipoDeAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTipoDeAnimal;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel txtEspacio;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
