/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.myfarm.frontend.dialogs.partida;

import com.mycompany.myfarm.backend.MotorJuego;
import com.mycompany.myfarm.backend.granja.Granja;
import com.mycompany.myfarm.backend.mercado.Mercado;
import com.mycompany.myfarm.backend.suelo.Suelo;
import com.mycompany.myfarm.backend.suelo.SueloGrama;
import com.mycompany.myfarm.frontend.paneles.Partida.Granja.PanelSinAccion;
import java.awt.GridLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author ronaldo
 */
public class CeldasParaSembrarDialog extends javax.swing.JDialog {
    private Suelo [][] suelos;
   
    /**
     * Creates new form CeldasParaSembrarDialog
     */
    public CeldasParaSembrarDialog(Suelo [][] suelos, int filas, int columnas) {
        initComponents();
        this.suelos=suelos;
        panelSuelos.setLayout(new GridLayout(filas, columnas, 2, 2));
        colocarPanelesAMatriz(filas, columnas);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblEncabezado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelSuelos = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnBuscarSemillas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(0, 204, 204));
        panelPrincipal.setForeground(new java.awt.Color(0, 204, 204));

        lblEncabezado.setBackground(new java.awt.Color(51, 204, 0));
        lblEncabezado.setFont(new java.awt.Font("Ubuntu Mono", 1, 36)); // NOI18N
        lblEncabezado.setForeground(new java.awt.Color(0, 0, 0));
        lblEncabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEncabezado.setText("SIEMBRA");
        lblEncabezado.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Ubuntu Mono", 0, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Seleccion los suelos donde se va a sembrar:");

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelSuelos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout panelSuelosLayout = new javax.swing.GroupLayout(panelSuelos);
        panelSuelos.setLayout(panelSuelosLayout);
        panelSuelosLayout.setHorizontalGroup(
            panelSuelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 906, Short.MAX_VALUE)
        );
        panelSuelosLayout.setVerticalGroup(
            panelSuelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelSuelos);

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Regresar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnBuscarSemillas.setBackground(new java.awt.Color(0, 204, 102));
        btnBuscarSemillas.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        btnBuscarSemillas.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarSemillas.setText("Elegir una semilla");
        btnBuscarSemillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSemillasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarSemillas, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPrincipalLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1)
                .addGap(39, 39, 39))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addComponent(lblEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarSemillas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarSemillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSemillasActionPerformed
        Granja granja = suelos[0][0].getGranja();
        if (granja.haySueloSeleccionado()) {
            Mercado mercado=MotorJuego.getAlmacenador().getMercadoGeneral();
            IniciarSiembraDialog dialog = new IniciarSiembraDialog(mercado.getSemillasDisponibles(), granja.getGranjero());
            dialog.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this,"Debes seleccionar almenos un suelo para sembrar", "Seleccionar", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnBuscarSemillasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Granja granja = suelos[0][0].getGranja();
        granja.quitarSeleccionadoASuelos();
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    //metodo que se encarga de ir colocando los paneles al panel de suelos
    private void colocarPanelesAMatriz(int filas, int columnas) {
        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                // cuando el suelo es grama se coloca un panel de disponibilidad
                if (suelos[i][j] instanceof SueloGrama) {
                    SueloGrama suelo = (SueloGrama) suelos[i][j];
                    int ancho = suelo.getPanelDisponibilidad().getWidth();
                    suelo.getPanelDisponibilidad().setSize(ancho, 80);
                    revalidate();
                    panelSuelos.add(suelo.getPanelDisponibilidad());
                    suelo.getPanelDisponibilidad().inicilizarFondoYLabelInfo();
                    revalidate();
                    repaint();
                } else {
                    panelSuelos.add(new PanelSinAccion());
                    revalidate();
                    repaint();
                }
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarSemillas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEncabezado;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuelos;
    // End of variables declaration//GEN-END:variables
}
