/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.myfarm.frontend.dialogs.partida;

import com.mycompany.myfarm.backend.MotorJuego;
import com.mycompany.myfarm.backend.granjero.Granjero;
import com.mycompany.myfarm.backend.listaEnlazada.ListaEnlazadaGenerica;
import com.mycompany.myfarm.backend.semilla.Semilla;

/**
 *
 * @author ronaldo
 */
public class IniciarSiembraDialog extends javax.swing.JDialog {
    private Granjero granjero;
    private ListaEnlazadaGenerica<Semilla> semillasMercado;
    /**
     * Creates new form IniciarSiembraDialog
     */
    public IniciarSiembraDialog(ListaEnlazadaGenerica<Semilla> semillasMercado, Granjero granjero) {
        initComponents();
        this.granjero=granjero;
        this.semillasMercado=semillasMercado;
        crearListaDeSemillas();
        btnIrAlMercado.setVisible(false);
        btnSembrar.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEncabezado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbListaSemillas = new javax.swing.JComboBox<>();
        lblAvisoCantidadSemillas = new javax.swing.JLabel();
        btnIrAlMercado = new javax.swing.JButton();
        btnSembrar = new javax.swing.JButton();
        btnDisponibilidad = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        lblEncabezado.setBackground(new java.awt.Color(0, 153, 51));
        lblEncabezado.setFont(new java.awt.Font("Ubuntu Mono", 1, 36)); // NOI18N
        lblEncabezado.setForeground(new java.awt.Color(0, 0, 0));
        lblEncabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEncabezado.setText("Iniciar Siembra");
        lblEncabezado.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Planta que quieres sembrar:");

        lblAvisoCantidadSemillas.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
        lblAvisoCantidadSemillas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnIrAlMercado.setBackground(new java.awt.Color(0, 51, 153));
        btnIrAlMercado.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        btnIrAlMercado.setText("Ir al mercado");
        btnIrAlMercado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrAlMercadoActionPerformed(evt);
            }
        });

        btnSembrar.setBackground(new java.awt.Color(0, 51, 153));
        btnSembrar.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        btnSembrar.setText("Sembrar");
        btnSembrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSembrarActionPerformed(evt);
            }
        });

        btnDisponibilidad.setBackground(new java.awt.Color(255, 255, 0));
        btnDisponibilidad.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        btnDisponibilidad.setForeground(new java.awt.Color(0, 0, 0));
        btnDisponibilidad.setText("Disponibilidad");
        btnDisponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisponibilidadActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(204, 51, 0));
        jLabel2.setText("Presiona en disponibilidad para ver si tienes las semillas suficientes para sembrar.");

        btnSalir.setBackground(new java.awt.Color(204, 0, 51));
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEncabezado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnIrAlMercado)
                        .addGap(103, 103, 103)
                        .addComponent(btnSembrar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(176, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbListaSemillas, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAvisoCantidadSemillas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbListaSemillas, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAvisoCantidadSemillas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSembrar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIrAlMercado, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSembrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSembrarActionPerformed
        Semilla semilla = semillasMercado.obtenerNodo(cmbListaSemillas.getSelectedIndex()).getContenido();
        granjero.sembrar(semilla);
        this.dispose();
    }//GEN-LAST:event_btnSembrarActionPerformed

    private void btnDisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisponibilidadActionPerformed
        int indiceSemilla=cmbListaSemillas.getSelectedIndex();
        Semilla semilla = semillasMercado.obtenerNodo(indiceSemilla).getContenido();
        boolean tieneSemillasNecesarias = granjero.haySemillasNecesariasParaSembrar(semilla);
        if (tieneSemillasNecesarias) {
            lblAvisoCantidadSemillas.setText("Puedes iniciar la siembra");
            btnSembrar.setVisible(true);
        } else {
            btnIrAlMercado.setVisible(true);
            lblAvisoCantidadSemillas.setText("Te faltan " + granjero.cantidadDeSemillasQueFaltan(semilla) + " semillas ve al mercado a comprar");
        }

    }//GEN-LAST:event_btnDisponibilidadActionPerformed

    private void btnIrAlMercadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrAlMercadoActionPerformed
        MercadoDialog dialog = new MercadoDialog(MotorJuego.getAlmacenador().getMercadoGeneral(), granjero);
        dialog.setVisible(true);
        btnIrAlMercado.setVisible(false);
    }//GEN-LAST:event_btnIrAlMercadoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        granjero.getGranja().quitarSeleccionadoASuelos();
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    //metodo que se encarga cargar el cmbbox con el nombre de cada semilla disponible
    private void crearListaDeSemillas(){
        for(int i=0; i<semillasMercado.getTamaño(); i++){
            cmbListaSemillas.addItem(""+semillasMercado.obtenerNodo(i).getContenido().getPlanta().getNombre());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisponibilidad;
    private javax.swing.JButton btnIrAlMercado;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSembrar;
    private javax.swing.JComboBox<String> cmbListaSemillas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAvisoCantidadSemillas;
    private javax.swing.JLabel lblEncabezado;
    // End of variables declaration//GEN-END:variables
}
