/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.myfarm.frontend.dialogs.partida;

import com.mycompany.myfarm.backend.MotorJuego;
import com.mycompany.myfarm.backend.listaEnlazada.ListaEnlazadaGenerica;
import com.mycompany.myfarm.backend.partida.Partida;
import javax.swing.JOptionPane;

/**
 *
 * @author ronaldo
 */
public class MenuInicioPartidaDialog extends javax.swing.JDialog {
    private ListaEnlazadaGenerica<Partida> partidasGuardadas;
    /**
     * Creates new form MenuInicioPartida
     */
    public MenuInicioPartidaDialog() {
        initComponents();
        setLocationRelativeTo(null);
        partidasGuardadas=MotorJuego.getAlmacenador().getPartidasGuardadas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEncabezado = new javax.swing.JLabel();
        btnNuevaPartida = new javax.swing.JButton();
        btnContinuarPartida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        lblEncabezado.setBackground(new java.awt.Color(0, 255, 153));
        lblEncabezado.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        lblEncabezado.setForeground(new java.awt.Color(0, 0, 0));
        lblEncabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEncabezado.setText("Menu Inicio Partida");
        lblEncabezado.setOpaque(true);

        btnNuevaPartida.setBackground(new java.awt.Color(51, 0, 255));
        btnNuevaPartida.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        btnNuevaPartida.setText("Iniciar Nueva Partida");
        btnNuevaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaPartidaActionPerformed(evt);
            }
        });

        btnContinuarPartida.setBackground(new java.awt.Color(0, 0, 255));
        btnContinuarPartida.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        btnContinuarPartida.setText("Continuar una Partida ");
        btnContinuarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarPartidaActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecciona una opcion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNuevaPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnContinuarPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(201, 201, 201))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(btnNuevaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnContinuarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaPartidaActionPerformed
        dispose();
        RegistroPartidaDialog dialog = new RegistroPartidaDialog();
        dialog.setVisible(true);


    }//GEN-LAST:event_btnNuevaPartidaActionPerformed

    private void btnContinuarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarPartidaActionPerformed
         this.dispose();
        if(partidasGuardadas.getTamaño()>0){
            SeleccionDePartidaDialog dialog= new SeleccionDePartidaDialog(partidasGuardadas);
            dialog.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this,"No hay partidas guardadas","sin partidas",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnContinuarPartidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuarPartida;
    private javax.swing.JButton btnNuevaPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEncabezado;
    // End of variables declaration//GEN-END:variables
}
