/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.myfarm.frontend.dialogs.partida;

import com.mycompany.myfarm.backend.animal.Animal;
import com.mycompany.myfarm.backend.granja.Bodega;
import com.mycompany.myfarm.backend.granjero.Granjero;
import com.mycompany.myfarm.backend.listaEnlazada.ListaEnlazadaGenerica;
import com.mycompany.myfarm.backend.listaEnlazada.NodoGenerico;
import com.mycompany.myfarm.backend.mercado.Mercado;
import com.mycompany.myfarm.backend.producto.Alimento;
import com.mycompany.myfarm.backend.producto.Producto;
import com.mycompany.myfarm.backend.semilla.Semilla;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ronaldo
 */
public class MercadoDialog extends javax.swing.JDialog {

    private Granjero granjero;
    private Mercado mercado;
    private Bodega bodega;

    /**
     * Creates new form MercadoDialog
     */
    public MercadoDialog(Mercado mercado, Granjero granjero) {
        initComponents();
        setLocationRelativeTo(null);
        panelVender.setVisible(false);
        ponerListaACombos(mercado);
        ponerInformacionATablas(mercado);
        this.granjero = granjero;
        this.mercado = mercado;
        cargarCmbCantidad();
        actualizarLabelDineroDisponible();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelSecundario = new javax.swing.JPanel();
        panelComprarSemillas = new javax.swing.JPanel();
        lblSemillas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaSemillas = new javax.swing.JTable();
        lnlSemillas = new javax.swing.JLabel();
        cmbSemillas = new javax.swing.JComboBox<>();
        btnComprarSemilla = new javax.swing.JButton();
        cmbCantidadSemillas = new javax.swing.JComboBox<>();
        lnlSemillas1 = new javax.swing.JLabel();
        panelAlimentos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaAlimentos = new javax.swing.JTable();
        lblTituloAlimentos = new javax.swing.JLabel();
        lblInfoAlimento = new javax.swing.JLabel();
        cmbAlimentos = new javax.swing.JComboBox<>();
        btnComprarAlimento = new javax.swing.JButton();
        lblInfoAlimento1 = new javax.swing.JLabel();
        cmbCantidaAnimales = new javax.swing.JComboBox<>();
        panelVender = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVenta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmbCantidad = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnVender = new javax.swing.JButton();
        panelEncabezado = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        lblDineroDisponible = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        panelSecundario.setBackground(new java.awt.Color(204, 255, 204));

        panelComprarSemillas.setBackground(new java.awt.Color(102, 255, 204));
        panelComprarSemillas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSemillas.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        lblSemillas.setForeground(new java.awt.Color(0, 0, 0));
        lblSemillas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSemillas.setText("Semillas a la venta");

        tablaSemillas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio", "Tipo", "Producto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaSemillas);

        lnlSemillas.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        lnlSemillas.setForeground(new java.awt.Color(0, 0, 0));
        lnlSemillas.setText("Selecciona la semilla");

        cmbSemillas.setFont(new java.awt.Font("Ubuntu Mono", 0, 21)); // NOI18N

        btnComprarSemilla.setBackground(new java.awt.Color(0, 102, 204));
        btnComprarSemilla.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        btnComprarSemilla.setForeground(new java.awt.Color(0, 0, 0));
        btnComprarSemilla.setText("Comprar");
        btnComprarSemilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarSemillaActionPerformed(evt);
            }
        });

        lnlSemillas1.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        lnlSemillas1.setForeground(new java.awt.Color(0, 0, 0));
        lnlSemillas1.setText("Cantidad");

        javax.swing.GroupLayout panelComprarSemillasLayout = new javax.swing.GroupLayout(panelComprarSemillas);
        panelComprarSemillas.setLayout(panelComprarSemillasLayout);
        panelComprarSemillasLayout.setHorizontalGroup(
            panelComprarSemillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComprarSemillasLayout.createSequentialGroup()
                .addGroup(panelComprarSemillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComprarSemillasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelComprarSemillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                            .addGroup(panelComprarSemillasLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(cmbSemillas, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(cmbCantidadSemillas, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnComprarSemilla))))
                    .addGroup(panelComprarSemillasLayout.createSequentialGroup()
                        .addGroup(panelComprarSemillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelComprarSemillasLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lblSemillas, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelComprarSemillasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lnlSemillas)
                                .addGap(44, 44, 44)
                                .addComponent(lnlSemillas1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelComprarSemillasLayout.setVerticalGroup(
            panelComprarSemillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComprarSemillasLayout.createSequentialGroup()
                .addComponent(lblSemillas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelComprarSemillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnlSemillas)
                    .addComponent(lnlSemillas1))
                .addGap(5, 5, 5)
                .addGroup(panelComprarSemillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSemillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComprarSemilla)
                    .addComponent(cmbCantidadSemillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAlimentos.setBackground(new java.awt.Color(51, 255, 255));
        panelAlimentos.setBorder(new javax.swing.border.MatteBorder(null));

        tablaAlimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Precio"
            }
        ));
        jScrollPane3.setViewportView(tablaAlimentos);

        lblTituloAlimentos.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        lblTituloAlimentos.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloAlimentos.setText("Alimentos a la venta");

        lblInfoAlimento.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        lblInfoAlimento.setForeground(new java.awt.Color(0, 0, 0));
        lblInfoAlimento.setText("Selecciona el alimento");

        btnComprarAlimento.setBackground(new java.awt.Color(255, 102, 0));
        btnComprarAlimento.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        btnComprarAlimento.setForeground(new java.awt.Color(0, 0, 0));
        btnComprarAlimento.setText("Comprar");
        btnComprarAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarAlimentoActionPerformed(evt);
            }
        });

        lblInfoAlimento1.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        lblInfoAlimento1.setForeground(new java.awt.Color(0, 0, 0));
        lblInfoAlimento1.setText("Cantidad");

        javax.swing.GroupLayout panelAlimentosLayout = new javax.swing.GroupLayout(panelAlimentos);
        panelAlimentos.setLayout(panelAlimentosLayout);
        panelAlimentosLayout.setHorizontalGroup(
            panelAlimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlimentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAlimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlimentosLayout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addGap(9, 9, 9))
                    .addGroup(panelAlimentosLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(cmbAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(cmbCantidaAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnComprarAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 65, Short.MAX_VALUE))))
            .addGroup(panelAlimentosLayout.createSequentialGroup()
                .addGroup(panelAlimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlimentosLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lblTituloAlimentos))
                    .addGroup(panelAlimentosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblInfoAlimento)
                        .addGap(54, 54, 54)
                        .addComponent(lblInfoAlimento1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelAlimentosLayout.setVerticalGroup(
            panelAlimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlimentosLayout.createSequentialGroup()
                .addComponent(lblTituloAlimentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAlimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfoAlimento)
                    .addComponent(lblInfoAlimento1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAlimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComprarAlimento)
                    .addComponent(cmbCantidaAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelVender.setBackground(new java.awt.Color(204, 204, 0));

        tablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Nombre", "Tipo", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tablaVenta);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("VENTA DE PRODUCTOS ");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cantidad a vender");

        btnVender.setText("Vender");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVenderLayout = new javax.swing.GroupLayout(panelVender);
        panelVender.setLayout(panelVenderLayout);
        panelVenderLayout.setHorizontalGroup(
            panelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVenderLayout.createSequentialGroup()
                .addGroup(panelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVenderLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelVenderLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(jLabel1))
                    .addGroup(panelVenderLayout.createSequentialGroup()
                        .addGroup(panelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelVenderLayout.createSequentialGroup()
                                .addGap(299, 299, 299)
                                .addComponent(cmbCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelVenderLayout.createSequentialGroup()
                                .addGap(307, 307, 307)
                                .addComponent(jLabel2)))
                        .addGap(44, 44, 44)
                        .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelVenderLayout.setVerticalGroup(
            panelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVenderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout panelSecundarioLayout = new javax.swing.GroupLayout(panelSecundario);
        panelSecundario.setLayout(panelSecundarioLayout);
        panelSecundarioLayout.setHorizontalGroup(
            panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSecundarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelVender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelSecundarioLayout.createSequentialGroup()
                        .addComponent(panelAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelComprarSemillas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelSecundarioLayout.setVerticalGroup(
            panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSecundarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelComprarSemillas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAlimentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelVender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelEncabezado.setBackground(new java.awt.Color(0, 204, 204));

        lblTitulo.setBackground(new java.awt.Color(0, 204, 204));
        lblTitulo.setFont(new java.awt.Font("Ubuntu Mono", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo.setText("Mercado");
        lblTitulo.setOpaque(true);

        btnRegresar.setBackground(new java.awt.Color(255, 51, 51));
        btnRegresar.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblDineroDisponible.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        lblDineroDisponible.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelEncabezadoLayout = new javax.swing.GroupLayout(panelEncabezado);
        panelEncabezado.setLayout(panelEncabezadoLayout);
        panelEncabezadoLayout.setHorizontalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblDineroDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        panelEncabezadoLayout.setVerticalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblDineroDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSecundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(panelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarSemillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarSemillaActionPerformed
        int precioDelProducto = mercado.getSemillasDisponibles().obtenerNodo(cmbSemillas.getSelectedIndex()).getContenido().getPrecioDeCompra();
        int indiceSemilla=cmbSemillas.getSelectedIndex();
        int cantidadDeSemillas = cmbCantidadSemillas.getSelectedIndex() + 1;
        int totalAPagar = precioDelProducto * cantidadDeSemillas;
        if (cmbSemillas.getSelectedIndex() != -1 && granjero.getOroDisponible() >= totalAPagar) {
            Semilla semilla = mercado.getSemillasDisponibles().obtenerNodo(indiceSemilla).getContenido();
            mercado.darleLasSemillasAlGranjero(granjero, semilla, cantidadDeSemillas);
            granjero.pagar(totalAPagar);
            mercado.getSemillasDisponibles().obtenerContenido(cmbSemillas.getSelectedIndex()).getPlanta().agregarSemillasCompradas(cantidadDeSemillas);
            actualizarLabelDineroDisponible();
            JOptionPane.showMessageDialog(this, "Compra realizada con exito", "Compra", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No cuentas con el dinero suficiente ", "Falta Dinero", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnComprarSemillaActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnComprarAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarAlimentoActionPerformed
        int cantidad = cmbCantidaAnimales.getSelectedIndex() + 1;
        int indiceAlimento = cmbAlimentos.getSelectedIndex();
        Alimento alimento = mercado.getAlimentosParaAnimales()[indiceAlimento];
        int total = cantidad * alimento.getPrecioDeVenta();
        if (granjero.getOroDisponible() >= total) {
            //se realiza la compra
            ListaEnlazadaGenerica<Alimento> alimentos = granjero.getGranja().getBodega().getAlimentosParaAnimales();
            mercado.devolverAlimentos(alimentos, cantidad, alimento);
            granjero.pagar(total);
            actualizarLabelDineroDisponible();
            JOptionPane.showMessageDialog(this, "Compra realizada con exito", "Compra", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No tiene dinero suficiente para realizar esta compra", "Falta dinero", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnComprarAlimentoActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        if (bodega.getProductosGuardados().getTamaño() > 0) {
            int cantidadAVender = cmbCantidad.getSelectedIndex() + 1;
            bodega.sacarProductos(cantidadAVender, granjero);
            actualizarLabelDineroDisponible();
            cargarTablaVenta();
            JOptionPane.showMessageDialog(this,"Venta exitosa","Venta",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this,"No tienes productos para vender","Sin productos",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnVenderActionPerformed

    public void cargarTablaVenta() {
        DefaultTableModel modelo = (DefaultTableModel) tablaVenta.getModel();
        int filas = modelo.getRowCount();
        for (int i = filas - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
        cmbCantidad.removeAllItems();
        for (int i = 0; i < bodega.getProductosGuardados().getTamaño(); i++) {
                Producto producto = bodega.getProductosGuardados().obtenerContenido(i);
                if (producto != null) {
                    modelo.addRow(new Object[]{(i + 1), producto.getNombre(), producto.getClass().getSimpleName(), producto.getPrecioDeVenta()});
                    cmbCantidad.addItem("" + (i + 1));
                }
            

        }

    }


    
    
    private void actualizarLabelDineroDisponible() {
        lblDineroDisponible.setText("Dinero Disponibles: " + granjero.getOroDisponible());
    }

    public void ponerListaACombos(Mercado mercado) {
        ponerListaDeAlimentosACmbAlimentos(mercado);
        ponerListaDeSemillasACmbSemillas(mercado);
    }

    public void ponerInformacionATablas(Mercado mercado) {

        ponerInfoATablaSemillas(mercado);
        ponerInfoEnTablaAlimentos(mercado);
    }

    private void ponerInfoATablaSemillas(Mercado mercado) {
        for (int i = 0; i < mercado.getSemillasDisponibles().getTamaño(); i++) {
            DefaultTableModel model = (DefaultTableModel) tablaSemillas.getModel();
            model.addRow(new Object[]{mercado.getSemillasDisponibles().obtenerNodo(i).getContenido().getNombre(), mercado.getSemillasDisponibles().obtenerNodo(i).getContenido().getPrecioDeCompra(),
                mercado.getSemillasDisponibles().obtenerNodo(i).getContenido().getPlanta().getClass().getSimpleName(), mercado.getSemillasDisponibles().obtenerNodo(i).getContenido().getPlanta().getProducto().getNombre()});
        }
    }

    private void ponerInfoEnTablaAlimentos(Mercado mercado) {
        DefaultTableModel model = (DefaultTableModel) tablaAlimentos.getModel();
        for (int i = 0; i < mercado.getAlimentosParaAnimales().length; i++) {
            model.addRow(new Object[]{mercado.getAlimentosParaAnimales()[i].getNombre(), obtenerTipoDeAlimento(mercado.getAlimentosParaAnimales()[i]),
                mercado.getAlimentosParaAnimales()[i].getPrecioDeVenta()});
        }
    }

    private void ponerListaDeSemillasACmbSemillas(Mercado mercado) {
        for (int i = 0; i < mercado.getSemillasDisponibles().getTamaño(); i++) {
            cmbSemillas.addItem(mercado.getSemillasDisponibles().obtenerNodo(i).getContenido().getNombre());
        }
    }

    private void ponerListaDeAlimentosACmbAlimentos(Mercado mercado) {
        for (int i = 0; i < mercado.getAlimentosParaAnimales().length; i++) {
            cmbAlimentos.addItem(mercado.getAlimentosParaAnimales()[i].getNombre());
        }
    }

    public String obtenerListaDeProductosDeUnAnimal(Animal animal) {
        String lista = "";
        for (int i = 0; i < animal.getProductos().getTamaño() - 1; i++) {
            if (i < animal.getProductos().getTamaño() - 1) {
                lista += animal.getProductos().obtenerContenido(i).getNombre() + ", ";
            } else {
                lista += animal.getProductos().obtenerContenido(i).getNombre();
            }
        }
        return lista;
    }

    public String esDestasable(Animal animal) {
        if (animal.isEsDestasable()) {
            return "Sí";
        }
        return "No";
    }

    public void cargarCmbCantidad() {
        for (int i = 1; i <= 100; i++) {
            cmbCantidadSemillas.addItem("" + i);
            cmbCantidaAnimales.addItem("" + i);
        }
    }

    public String obtenerTipoDeAlimento(Alimento alimento) {
        if (alimento.isParaHervivoros()) {
            return "Para herbivoros";
        }
        return "Para Omnivoros";
    }

    public Bodega getBodega() {
        return bodega;
    }

    public void setBodega(Bodega bodega) {
        this.bodega = bodega;
    }

    public void setPanelVender(JPanel panelVender) {
        this.panelVender = panelVender;
    }

    public JPanel getPanelVender() {
        return panelVender;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprarAlimento;
    private javax.swing.JButton btnComprarSemilla;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVender;
    private javax.swing.JComboBox<String> cmbAlimentos;
    private javax.swing.JComboBox<String> cmbCantidaAnimales;
    private javax.swing.JComboBox<String> cmbCantidad;
    private javax.swing.JComboBox<String> cmbCantidadSemillas;
    private javax.swing.JComboBox<String> cmbSemillas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDineroDisponible;
    private javax.swing.JLabel lblInfoAlimento;
    private javax.swing.JLabel lblInfoAlimento1;
    private javax.swing.JLabel lblSemillas;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloAlimentos;
    private javax.swing.JLabel lnlSemillas;
    private javax.swing.JLabel lnlSemillas1;
    private javax.swing.JPanel panelAlimentos;
    private javax.swing.JPanel panelComprarSemillas;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSecundario;
    private javax.swing.JPanel panelVender;
    private javax.swing.JTable tablaAlimentos;
    private javax.swing.JTable tablaSemillas;
    private javax.swing.JTable tablaVenta;
    // End of variables declaration//GEN-END:variables
}
