/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.myfarm.frontend.dialogs.partida;

import com.mycompany.myfarm.backend.suelo.SueloAgua;
import com.mycompany.myfarm.frontend.paneles.Partida.Granja.PanelGranja;
import com.mycompany.myfarm.frontend.paneles.Partida.Granja.PanelSueloAgua;
import java.awt.Color;
import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author ronaldo
 */
public class PescarDialog extends javax.swing.JDialog {
    private SueloAgua suelo;
    private static final String PATH_CARPETA = "imagenes";
    /**
     * Creates new form PescarDialog
     */
    public PescarDialog(int cantidadDeMonedas, SueloAgua suelo) {
        setTitle("Pescar");
        initComponents();
        setLocationRelativeTo(null);
        this.suelo=suelo;
        lblMonedasDisponibles.setText("Monedas: "+cantidadDeMonedas);
        lblPrecioBarco.setText("Precio de un barco: "+suelo.getPRECIO_DE_BARCO());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblEncabezado = new javax.swing.JLabel();
        lblMonedasDisponibles = new javax.swing.JLabel();
        lblPrecioBarco = new javax.swing.JLabel();
        btnComprarPescar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        panelPrincipal.setBackground(new java.awt.Color(102, 153, 255));

        lblEncabezado.setBackground(new java.awt.Color(0, 102, 102));
        lblEncabezado.setFont(new java.awt.Font("Ubuntu Mono", 1, 36)); // NOI18N
        lblEncabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEncabezado.setText("PESCA");
        lblEncabezado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblEncabezado.setOpaque(true);

        lblMonedasDisponibles.setBackground(new java.awt.Color(0, 153, 153));
        lblMonedasDisponibles.setFont(new java.awt.Font("Ubuntu Mono", 1, 36)); // NOI18N
        lblMonedasDisponibles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMonedasDisponibles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblMonedasDisponibles.setOpaque(true);

        lblPrecioBarco.setFont(new java.awt.Font("Ubuntu Mono", 0, 24)); // NOI18N
        lblPrecioBarco.setForeground(new java.awt.Color(51, 204, 255));
        lblPrecioBarco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnComprarPescar.setText("Comprar y Pescar");
        btnComprarPescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarPescarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(lblEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMonedasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComprarPescar)
                .addGap(43, 43, 43))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(lblPrecioBarco, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMonedasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(lblPrecioBarco, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnComprarPescar, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarPescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarPescarActionPerformed
        if (suelo.getGranja().getGranjero().getOroDisponible() >= suelo.getPRECIO_DE_BARCO()) {
            suelo.getGranja().getGranjero().pagar(suelo.getPRECIO_DE_BARCO());
            suelo.setHayBarco(true);
            suelo.getPanel().getLblIcono().setIcon(new ImageIcon(getClass().getClassLoader().getResource(PATH_CARPETA + File.separator + "iconoPescando.png")));
            suelo.getPanel().setBackground(new Color(51, 204, 255));
            Thread hilo = new Thread(suelo);
            hilo.start();
            this.dispose();
        }
    }//GEN-LAST:event_btnComprarPescarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprarPescar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblEncabezado;
    private javax.swing.JLabel lblMonedasDisponibles;
    private javax.swing.JLabel lblPrecioBarco;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
