/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.myfarm.frontend.dialogs;

import com.mycompany.myfarm.backend.MotorJuego;
import com.mycompany.myfarm.backend.creadores.CreadorDePlantas;
import com.mycompany.myfarm.backend.producto.AlimentoFruto;
import com.mycompany.myfarm.backend.producto.AlimentoGrano;
import com.mycompany.myfarm.backend.producto.Producto;

/**
 *
 * @author ronaldo
 */
public class SeleccionProductosPlantaDialog extends javax.swing.JDialog {
    private CreadorDePlantas creador;
    /**
     * Creates new form SeleccionProductosPlantaDialog
     */
    public SeleccionProductosPlantaDialog(int tipoDeAlimento) {
        initComponents();
        setLocationRelativeTo(null);
        agregarElListadoDeProductosAlCmbbox(tipoDeAlimento);
        creador= new CreadorDePlantas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lblEncabezado = new javax.swing.JLabel();
        cmbProductos = new javax.swing.JComboBox<>();
        btnAgregarProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        panel.setBackground(new java.awt.Color(0, 204, 204));

        lblEncabezado.setBackground(new java.awt.Color(255, 51, 51));
        lblEncabezado.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        lblEncabezado.setForeground(new java.awt.Color(0, 0, 0));
        lblEncabezado.setText("Selecciona el producto que generará la planta");
        lblEncabezado.setOpaque(true);

        btnAgregarProducto.setBackground(new java.awt.Color(204, 204, 204));
        btnAgregarProducto.setFont(new java.awt.Font("Ubuntu Mono", 1, 19)); // NOI18N
        btnAgregarProducto.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarProducto.setText("Agregar");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(cmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(lblEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(btnAgregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        String nombreDeProducto=(String)cmbProductos.getSelectedItem();
        creador.buscarYAgregarProductoAPlanta(nombreDeProducto);
        this.dispose();
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void agregarElListadoDeProductosAlCmbbox(int tipoDeAlimemto) {
        for (int i = 0; i < MotorJuego.getAlmacenador().getProductosDisponibles().getTamaño(); i++) {
            Producto producto = MotorJuego.getAlmacenador().getProductosDisponibles().obtenerContenido(i);
            if (tipoDeAlimemto == 1) {
                if (producto instanceof AlimentoGrano) {
                    cmbProductos.addItem(producto.getNombre() + "");
                }
            } else {
                if (producto instanceof AlimentoFruto) {
                    cmbProductos.addItem(producto.getNombre() + "");
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JComboBox<String> cmbProductos;
    private javax.swing.JLabel lblEncabezado;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
