/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.myfarm.frontend.paneles.Partida.Granja;

import com.mycompany.myfarm.backend.cola.exception.ListaEnlazadaException;
import com.mycompany.myfarm.backend.granja.Bodega;
import com.mycompany.myfarm.backend.granjero.Granjero;
import com.mycompany.myfarm.backend.producto.Alimento;
import com.mycompany.myfarm.frontend.dialogs.AccionExitosaDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ronaldo
 */
public class ComerDialog extends javax.swing.JDialog {
    private Bodega bodega;
    private Granjero granjero;
    private static final int ENERGIA_POR_ALIMENTO=5;
    
    /**
     * Creates new form ComerDialog
     */
    public ComerDialog(Bodega bodega,Granjero granjero) {
        initComponents();
        this.bodega=bodega;
        this.granjero=granjero;
        setLocationRelativeTo(null);
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlimentos = new javax.swing.JTable();
        cmbNumeroAlimento = new javax.swing.JComboBox<>();
        btnComer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        panelPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Ubuntu Mono", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COMER");
        jLabel1.setOpaque(true);

        tablaAlimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Nombre"
            }
        ));
        jScrollPane1.setViewportView(tablaAlimentos);

        cmbNumeroAlimento.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N

        btnComer.setText("Comer");
        btnComer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComerActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Selecciona el No. del alimento que quieres comer");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(cmbNumeroAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnComer, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnComer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbNumeroAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 104, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComerActionPerformed
        if (bodega.getProductosGuardados().getTamaño() > 0) {
            try {
                int indiceComida = cmbNumeroAlimento.getSelectedIndex();
                    bodega.getProductosGuardados().eliminar(indiceComida);
                    granjero.agregarAlimentoConsumido();
                    int vidaTotal = granjero.getPuntosDeVida() + ENERGIA_POR_ALIMENTO;
                    if (vidaTotal > granjero.getLIMITE_PUNTOS_DE_VIDA()) {
                        granjero.setPuntosDeVida(granjero.getLIMITE_PUNTOS_DE_VIDA());
                    } else {
                        granjero.setPuntosDeVida(vidaTotal);
                    }
                    actualizarTabla();
                    //granjero.getGranja().getPanelGranja().getLblVida().setText("HP: " + granjero.getPuntosDeVida() + "/" + granjero.getLIMITE_PUNTOS_DE_VIDA());
                    AccionExitosaDialog accion = new AccionExitosaDialog("Has comido");
                    accion.setVisible(true);


            } catch (ListaEnlazadaException ex) {
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ya no hay alimentos en bodega", "Sin alimentos", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnComerActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //granjero.getGranja().getPanelGranja().getLblVida().setText("HP: "+granjero.getPuntosDeVida()+"/"+granjero.getLIMITE_PUNTOS_DE_VIDA());
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    public void actualizarTabla(){
        DefaultTableModel modelo =(DefaultTableModel) tablaAlimentos.getModel();
        int filas=modelo.getRowCount();
        for (int i = filas-1; i>=0; i--) {
            modelo.removeRow(i);
        }
        cmbNumeroAlimento.removeAllItems();
        for (int i = 0; i < bodega.getProductosGuardados().getTamaño(); i++) {
            if (bodega.getProductosGuardados().obtenerContenido(i) instanceof Alimento) {
                Alimento alimento =(Alimento)bodega.getProductosGuardados().obtenerContenido(i);
                modelo.addRow(new Object[]{(i + 1),alimento.getNombre()});
                cmbNumeroAlimento.addItem(""+(i+1));
            }
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComer;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbNumeroAlimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tablaAlimentos;
    // End of variables declaration//GEN-END:variables
}
