/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.myfarm.frontend.paneles.Partida.Granja;

import com.mycompany.myfarm.backend.Archivador;
import com.mycompany.myfarm.backend.MotorJuego;
import com.mycompany.myfarm.backend.ResumenPartida;
import com.mycompany.myfarm.backend.granja.Granja;
import com.mycompany.myfarm.backend.mercado.Mercado;
import com.mycompany.myfarm.frontend.FramePrograma;
import com.mycompany.myfarm.frontend.dialogs.partida.BodegaDialog;
import com.mycompany.myfarm.frontend.dialogs.partida.CeldasParaSembrarDialog;
import com.mycompany.myfarm.frontend.dialogs.partida.CosechasDialog;
import com.mycompany.myfarm.frontend.dialogs.partida.MercadoDialog;
import com.mycompany.myfarm.frontend.dialogs.partida.parcela.CrearParcelaDialgo;
import com.mycompany.myfarm.frontend.dialogs.partida.parcela.SeleccionParcelaDialog;
import com.mycompany.myfarm.frontend.dialogs.partida.PagarLimpiezaDialog;
import com.mycompany.myfarm.frontend.dialogs.partida.PartidaAcabadaDialog;
import com.mycompany.myfarm.frontend.dialogs.partida.parcela.VerParcelasDialog;
import com.mycompany.myfarm.frontend.paneles.PanelMenuJuego;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ronaldo
 */
public class PanelGranja extends javax.swing.JPanel implements Runnable {

    private static Granja granja;
    private CosechasDialog dialogCosechar;
    private boolean yaSeAviso;

    /**
     * Creates new form PanelGranja
     */
    public PanelGranja(Granja granja) {
        initComponents();
        this.granja = granja;
        panelTerreno.setLayout(new GridLayout(granja.getFilas(), granja.getColumnas(), 2, 2));
        colocarPanelesEnTerreno(granja);
        dialogCosechar = new CosechasDialog();
        lblNombre.setText(granja.getGranjero().getNick());
        lblVida.setText("HP:" + granja.getGranjero().getPuntosDeVida() + "/" + granja.getGranjero().getLIMITE_PUNTOS_DE_VIDA());
    }

    @Override
    public void run() {
        while (granja.getGranjero().isEstaVivo() && !granja.isActualizarPanelGranja() && !granja.getGranjero().isSalioDeLaPartida()) {
            actualizarHpGranjero();
            if (granja.getGranjero().getPuntosDeVida() <= 0) {
                granja.getGranjero().setEstaVivo(false);
            }
            actualizarHpGranjero();
        }
        if (!granja.getGranjero().isEstaVivo()) {
            PartidaAcabadaDialog dialog = new PartidaAcabadaDialog();
            dialog.setVisible(true);
        }
    }

    public void actualizarHpGranjero() {
        lblVida.setText("HP:" + granja.getGranjero().getPuntosDeVida() + "/" + granja.getGranjero().getLIMITE_PUNTOS_DE_VIDA());
        if (granja.getGranjero().getPuntosDeVida() <= 20 && !yaSeAviso) {
            JOptionPane.showMessageDialog(this, "Debes comer, te queda poca vida", "Comer", JOptionPane.ERROR_MESSAGE);
            yaSeAviso = true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEcabezado = new javax.swing.JPanel();
        btnGuardarYSalir = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBodega = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelPerfilJugador = new javax.swing.JPanel();
        lblVida = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblComer = new javax.swing.JLabel();
        btnMercado = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblSembrar = new javax.swing.JLabel();
        lblCosechar = new javax.swing.JLabel();
        lblLimpiarTodo = new javax.swing.JLabel();
        lblCrearParcela = new javax.swing.JLabel();
        lblCriar = new javax.swing.JLabel();
        lblVerParcelas = new javax.swing.JLabel();
        panelScroll = new javax.swing.JScrollPane();
        panelTerreno = new javax.swing.JPanel();

        setBackground(new java.awt.Color(51, 255, 204));

        panelEcabezado.setBackground(new java.awt.Color(255, 255, 102));
        panelEcabezado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelEcabezado.setForeground(new java.awt.Color(0, 0, 0));

        btnGuardarYSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardarYSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardarYSalir.setText("Guardar y salir");
        btnGuardarYSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGuardarYSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarYSalirMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu Mono", 1, 27)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MY FARM");

        lblBodega.setForeground(new java.awt.Color(0, 0, 0));
        lblBodega.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBodega.setText("BODEGA");
        lblBodega.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblBodega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBodegaMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 204, 0));

        panelPerfilJugador.setBackground(new java.awt.Color(153, 255, 0));
        panelPerfilJugador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblVida.setText("jLabel1");

        lblNombre.setText("jLabel1");

        javax.swing.GroupLayout panelPerfilJugadorLayout = new javax.swing.GroupLayout(panelPerfilJugador);
        panelPerfilJugador.setLayout(panelPerfilJugadorLayout);
        panelPerfilJugadorLayout.setHorizontalGroup(
            panelPerfilJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilJugadorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelPerfilJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVida, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelPerfilJugadorLayout.setVerticalGroup(
            panelPerfilJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilJugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        lblComer.setForeground(new java.awt.Color(0, 0, 0));
        lblComer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComer.setText("Comer");
        lblComer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblComer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblComerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblComer, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPerfilJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelPerfilJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblComer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMercado.setForeground(new java.awt.Color(0, 0, 0));
        btnMercado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMercado.setText("MERCADO");
        btnMercado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMercado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMercadoMouseClicked(evt);
            }
        });

        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelEcabezadoLayout = new javax.swing.GroupLayout(panelEcabezado);
        panelEcabezado.setLayout(panelEcabezadoLayout);
        panelEcabezadoLayout.setHorizontalGroup(
            panelEcabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEcabezadoLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBodega, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnMercado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarYSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        panelEcabezadoLayout.setVerticalGroup(
            panelEcabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelEcabezadoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelEcabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelEcabezadoLayout.createSequentialGroup()
                        .addGroup(panelEcabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBodega, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMercado, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardarYSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setBackground(new java.awt.Color(255, 51, 0));
        jLabel3.setFont(new java.awt.Font("Ubuntu Mono", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Acciones");
        jLabel3.setOpaque(true);

        lblSembrar.setForeground(new java.awt.Color(0, 0, 0));
        lblSembrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSembrar.setText("SEMBRAR");
        lblSembrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSembrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSembrarMouseClicked(evt);
            }
        });

        lblCosechar.setForeground(new java.awt.Color(0, 0, 0));
        lblCosechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCosechar.setText("COSECHAR");
        lblCosechar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCosechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCosecharMouseClicked(evt);
            }
        });

        lblLimpiarTodo.setForeground(new java.awt.Color(0, 0, 0));
        lblLimpiarTodo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLimpiarTodo.setText("LIMPIAR TODO");
        lblLimpiarTodo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblLimpiarTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLimpiarTodoMouseClicked(evt);
            }
        });

        lblCrearParcela.setForeground(new java.awt.Color(0, 0, 0));
        lblCrearParcela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCrearParcela.setText("CREAR PARCELA");
        lblCrearParcela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCrearParcela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCrearParcelaMouseClicked(evt);
            }
        });

        lblCriar.setForeground(new java.awt.Color(0, 0, 0));
        lblCriar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCriar.setText("CRIAR ");
        lblCriar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCriar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCriarMouseClicked(evt);
            }
        });

        lblVerParcelas.setForeground(new java.awt.Color(0, 0, 0));
        lblVerParcelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVerParcelas.setText("VER PARCELAS");
        lblVerParcelas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblVerParcelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerParcelasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblLimpiarTodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCrearParcela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCosechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSembrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblCriar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVerParcelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSembrar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCosechar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLimpiarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCrearParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVerParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        panelTerreno.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelTerrenoLayout = new javax.swing.GroupLayout(panelTerreno);
        panelTerreno.setLayout(panelTerrenoLayout);
        panelTerrenoLayout.setHorizontalGroup(
            panelTerrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
        );
        panelTerrenoLayout.setVerticalGroup(
            panelTerrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        panelScroll.setViewportView(panelTerreno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEcabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(panelScroll)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEcabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelScroll)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarYSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarYSalirMouseClicked
        granja.getGranjero().setSalioDeLaPartida(true);
        granja.detenerTodo();
        if (!MotorJuego.getAlmacenador().nombreDePartidaExistente(granja.getPartida().getNombre())) {
            MotorJuego.getAlmacenador().getPartidasGuardadas().agregarElemento(granja.getPartida());
        } else {
            MotorJuego.getAlmacenador().sobreEscribirPartida(granja.getPartida());
        }

        Archivador archivador = new Archivador();
        ResumenPartida resumen = MotorJuego.getAlmacenador().devolverResumenPartida(granja.getPartida());
        boolean yaExisteResumen = MotorJuego.getAlmacenador().getReporte().existeElResumen(granja.getGranjero().getNombre());

        if (yaExisteResumen) {
            int indiceAlmacenado = MotorJuego.getAlmacenador().getReporte()
                    .indiceDondeSeAlmacenaResumen(granja.getGranjero().getNombre());
            MotorJuego.getAlmacenador().getReporte().getResumenes()
                    .obtenerNodo(indiceAlmacenado).setContenido(resumen);
        } else {
            MotorJuego.getAlmacenador().getReporte().getResumenes().agregarElemento(resumen);
        }
        archivador.guardarReporte(MotorJuego.getAlmacenador().getReporte());
        FramePrograma.ponerPanelEnFramePrincipal(new PanelMenuJuego());
    }//GEN-LAST:event_btnGuardarYSalirMouseClicked

    private void lblBodegaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBodegaMouseClicked
        BodegaDialog dialog = new BodegaDialog(granja.getBodega(), granja.getGranjero().getSemillas());
        dialog.setVisible(true);
    }//GEN-LAST:event_lblBodegaMouseClicked

    private void lblSembrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSembrarMouseClicked
        CeldasParaSembrarDialog dialog = new CeldasParaSembrarDialog(granja.getSuelos(), granja.getFilas(), granja.getColumnas());
        dialog.setVisible(true);
    }//GEN-LAST:event_lblSembrarMouseClicked

    private void lblCosecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCosecharMouseClicked
        dialogCosechar.setGranja(granja);
        dialogCosechar.setCorriendoHilo(true);
        Thread hilo = new Thread(dialogCosechar);
        hilo.start();
        dialogCosechar.setVisible(true);
    }//GEN-LAST:event_lblCosecharMouseClicked

    private void lblLimpiarTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarTodoMouseClicked
        int precioDeLimpieza = granja.calcularPrecioLimpieza();
        if (precioDeLimpieza != 0) {
            PagarLimpiezaDialog dialog = new PagarLimpiezaDialog(granja.getGranjero(), precioDeLimpieza);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No hay celdas para limpiar", "Terreno limpio", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_lblLimpiarTodoMouseClicked

    private void lblComerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComerMouseClicked
        // el granjero come
        if (granja.hayAlimentosEnBodega()) {
            ComerDialog dialog = new ComerDialog(granja.getBodega(), granja.getGranjero());
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No hay alimentos en bodega", "Sin alimentos", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_lblComerMouseClicked
    // se crea una nueva parcela
    private void lblCrearParcelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearParcelaMouseClicked
        CrearParcelaDialgo dialog = new CrearParcelaDialgo(granja);
        dialog.setVisible(true);
    }//GEN-LAST:event_lblCrearParcelaMouseClicked

    private void lblCriarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCriarMouseClicked
        if (granja.getParcelas().getTamaño() > 0) {
            Mercado mercado = MotorJuego.getAlmacenador().getMercadoGeneral();
            SeleccionParcelaDialog dialog = new SeleccionParcelaDialog(granja, mercado);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No hay parcelas creadas", "Sin parcelas", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_lblCriarMouseClicked

    private void lblVerParcelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerParcelasMouseClicked
        if (granja.getParcelas().getTamaño() > 0) {
            VerParcelasDialog dialog = new VerParcelasDialog(granja);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No hay parcelas,crea uno", "Sin parcelas", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_lblVerParcelasMouseClicked

    private void btnMercadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMercadoMouseClicked
        Mercado mercado = MotorJuego.getAlmacenador().getMercadoGeneral();
        MercadoDialog dialog = new MercadoDialog(mercado, granja.getGranjero());
        if (granja.getBodega().getProductosGuardados().getTamaño() > 0) {
            dialog.setBodega(granja.getBodega());
            dialog.cargarTablaVenta();
            dialog.getPanelVender().setVisible(true);
        }
        dialog.setVisible(true);
    }//GEN-LAST:event_btnMercadoMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        granja.getGranjero().setSalioDeLaPartida(true);
        granja.getControladorHilos().terminarTodo();
        FramePrograma.ponerPanelEnFramePrincipal(new PanelMenuJuego());
    }//GEN-LAST:event_btnSalirMouseClicked

    public void colocarPanelesEnTerreno(Granja granja) {
        panelTerreno.removeAll();
        for (int i = 0; i < granja.getFilas(); i++) {
            for (int j = 0; j < granja.getColumnas(); j++) {
                if (granja.getSuelos()[i][j] != null) {
                    panelTerreno.add(granja.getSuelos()[i][j].getPanel());
                    revalidate();
                    repaint();
                } else {
                    int[] posicion = new int[]{i, j};
                    panelTerreno.add(new PanelSueloEnVenta(posicion, granja));
                    revalidate();
                    repaint();
                }
            }
        }
    }

    public CosechasDialog getDialogCosechar() {
        return dialogCosechar;
    }

    public void setDialogCosechar(CosechasDialog dialogCosechar) {
        this.dialogCosechar = dialogCosechar;
    }

    public JLabel getLblNombre() {
        return lblNombre;
    }

    public void setLblNombre(JLabel lblNombre) {
        this.lblNombre = lblNombre;
    }

    public JLabel getLblVida() {
        return lblVida;
    }

    public void setLblVida(JLabel lblVida) {
        this.lblVida = lblVida;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnGuardarYSalir;
    private javax.swing.JLabel btnMercado;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBodega;
    private javax.swing.JLabel lblComer;
    private javax.swing.JLabel lblCosechar;
    private javax.swing.JLabel lblCrearParcela;
    private javax.swing.JLabel lblCriar;
    private javax.swing.JLabel lblLimpiarTodo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSembrar;
    private javax.swing.JLabel lblVerParcelas;
    private javax.swing.JLabel lblVida;
    private javax.swing.JPanel panelEcabezado;
    private javax.swing.JPanel panelPerfilJugador;
    private javax.swing.JScrollPane panelScroll;
    private static javax.swing.JPanel panelTerreno;
    // End of variables declaration//GEN-END:variables


}
