/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.myfarm.frontend.paneles.Partida.Granja;

import com.mycompany.myfarm.backend.suelo.SueloGrama;
import java.awt.Color;


/**
 *
 * @author ronaldo
 */
public class PanelDisponibilidad extends javax.swing.JPanel{
    private SueloGrama suelo;
    private boolean fueSeleccionado;
    
    /**
     * Creates new form PanelDisponibilidad
     */
    public PanelDisponibilidad(SueloGrama suelo) {
        initComponents();
        this.suelo=suelo;
        inicilizarFondoYLabelInfo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDisponible = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblDisponible.setForeground(new java.awt.Color(0, 0, 0));
        lblDisponible.setText("No diponible");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if(!suelo.isEstaOcupado()){
            if(!suelo.isSeleccionada()){    
                lblDisponible.setText("Ocupado");
                suelo.setSeleccionada(true);
                fueSeleccionado=true;
                setBackground(Color.RED);
            }
            else {
                lblDisponible.setText("Disponible");
                suelo.setSeleccionada(false);
                fueSeleccionado=false;
                setBackground(Color.GREEN);
            }
        }
    }//GEN-LAST:event_formMouseClicked

    public void inicilizarFondoYLabelInfo(){
        if(!suelo.isEstaOcupado()){
            setBackground(Color.GREEN);
            lblDisponible.setText("Disponible");
        }
    }

    public boolean isFueSeleccionado() {
        return fueSeleccionado;
    }

    public void setFueSeleccionado(boolean fueSeleccionado) {
        this.fueSeleccionado = fueSeleccionado;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDisponible;
    // End of variables declaration//GEN-END:variables
}
