/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.myfarm.frontend.paneles.Partida.Granja;

import com.mycompany.myfarm.backend.MotorJuego;
import com.mycompany.myfarm.backend.planta.PlantaGrano;
import com.mycompany.myfarm.backend.suelo.SueloGrama;
import com.mycompany.myfarm.frontend.dialogs.partida.FertilizantesDialog;
import java.awt.Color;
import java.io.File;
import java.io.Serializable;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ronaldo
 */
public class PanelSueloGrama extends javax.swing.JPanel implements Serializable{
    private SueloGrama suelo;
    private static final String PATH_CARPETA = "imagenes";

    /**
     * Creates new form PanelSueloGrama
     */
    public PanelSueloGrama(SueloGrama suelo) {
        initComponents();
        this.suelo = suelo;
        lblTiempo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcono = new javax.swing.JLabel();
        lblTiempo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 102));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoGrama.png"))); // NOI18N

        lblTiempo.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        lblTiempo.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblTiempo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarIcono(int opcion) {
        if (opcion == 0) {
            setBackground(new Color(0, 204, 102));
            lblIcono.setIcon(new ImageIcon(getClass().getClassLoader().getResource(PATH_CARPETA + File.separator + "iconoGrama.png")));
            lblTiempo.setText("");
        } else if (opcion == 1) {
            setBackground(Color.GREEN);
            lblIcono.setIcon(new ImageIcon(getClass().getClassLoader().getResource(PATH_CARPETA + File.separator + "iconoSiembra.png")));
        } else if (opcion == 2) {
            setBackground(Color.ORANGE);
            if (suelo.getPlanta() instanceof PlantaGrano) {
                lblIcono.setIcon(new ImageIcon(getClass().getClassLoader().getResource(PATH_CARPETA + File.separator + "iconoGrano.png")));
            } else {
                lblIcono.setIcon(new ImageIcon(getClass().getClassLoader().getResource(PATH_CARPETA + File.separator + "iconoFruto.png")));
            }
        } else if (opcion == 3) {
            lblIcono.setIcon(new ImageIcon(getClass().getClassLoader().getResource(PATH_CARPETA + File.separator + "iconoFrutoPodrido.png")));
        } else if (opcion == 4) {
            lblIcono.setIcon(new ImageIcon(getClass().getClassLoader().getResource(PATH_CARPETA + File.separator + "iconoParcela.png")));
        } else if (opcion == 5) {
            lblIcono.setIcon(new ImageIcon(getClass().getClassLoader().getResource(PATH_CARPETA + File.separator + "iconoAnimal.png")));
            lblTiempo.setText("");
        } else if (opcion == 6) {
            lblIcono.setIcon(new ImageIcon(getClass().getClassLoader().getResource(PATH_CARPETA + File.separator + "iconoComida.png")));
            lblTiempo.setText("comida");
        }

    }

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (suelo.isEstaSucio()) {
            if (suelo.getGranja().getGranjero().getOroDisponible() >= 5) {
                suelo.setEstaSucio(false);
                suelo.setEstaOcupado(false);
                suelo.setYaTieneFertilizante(false);
                suelo.setPlanta(null);
                actualizarIcono(0);
                JOptionPane.showMessageDialog(this, "Celda limpiada", "Limpieza", JOptionPane.INFORMATION_MESSAGE);
            }
        } else if (suelo.getPlanta() != null) {
            if (suelo.getPlanta().isEstaCreciendo()) {
                if (!suelo.isYaTieneFertilizante()) {
                    FertilizantesDialog dialog = new FertilizantesDialog(MotorJuego.getAlmacenador().getMercadoGeneral().getFertilizantes(), suelo.getGranja().getGranjero(), suelo);
                    dialog.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "ya pusiste fertilizante", "Fertilizante", JOptionPane.ERROR_MESSAGE);
                }
            }

        }
    }//GEN-LAST:event_formMouseClicked

    public void setLblTiempo(JLabel lblTiempo) {
        this.lblTiempo = lblTiempo;
    }

    public JLabel getLblTiempo() {
        return lblTiempo;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblTiempo;
    // End of variables declaration//GEN-END:variables
}
