package com.mycompany.myfarm.frontend.paneles.Partida.Granja;
import com.mycompany.myfarm.backend.suelo.SueloAgua;
import com.mycompany.myfarm.frontend.dialogs.partida.PescarDialog;
import java.awt.Color;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ronaldo
 */
public class PanelSueloAgua extends javax.swing.JPanel implements Runnable{
    private static final String PATH_CARPETA="imagenes";
    private SueloAgua suelo;
    private boolean haSidoPresionado;

    public PanelSueloAgua(SueloAgua suelo) {
        initComponents();
        this.suelo = suelo;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcono = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblIcono.setBackground(new java.awt.Color(51, 255, 204));
        lblIcono.setForeground(new java.awt.Color(0, 0, 0));
        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoAgua.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lblIcono)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
       
        if (!suelo.isHayBarco()) {
            int monedasDelJugador = suelo.getGranja().getGranjero().getOroDisponible();
            //muestra un dialog que se encarga de hacer la transaccion del barco
            if (monedasDelJugador >= suelo.getPRECIO_DE_BARCO()) {
                PescarDialog dialog = new PescarDialog(monedasDelJugador, suelo);
                dialog.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No cuentas con suficientes monedas", "Faltan monedas", JOptionPane.INFORMATION_MESSAGE);
            }
            
        } 
        else if (suelo.isHayBarco() && suelo.getCantidadDePeces()==0) {
            
            suelo.setHayBarco(false);
            lblIcono.setText("");
            setBackground(new Color(0, 0, 255));
            lblIcono.setIcon(new ImageIcon(getClass().getClassLoader().getResource(PATH_CARPETA + File.separator + "iconoAgua.png")));
            Thread hilo = new Thread(suelo);
            hilo.start();
        }

    }//GEN-LAST:event_formMouseClicked

    public void informarQueYaNoHayPeces(){
        lblIcono.setIcon(null);
        lblIcono.setText("Sin peces, quita el barco");
    }
    public JLabel getLblIcono() {
        return lblIcono;
    }

    public void setLblIcono(JLabel lblIcono) {
        this.lblIcono = lblIcono;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblIcono;
    // End of variables declaration//GEN-END:variables

        @Override
        public void run() {
            System.out.println("inicio hilo");
           while(hayPeces()){ 
           }
            System.out.println("no hay peces");
           lblIcono.setIcon(null);
           lblIcono.setText("Quita el barco");
        }

    public boolean hayPeces() {
        if (suelo.getCantidadDePeces() > 0) {
            return true;
        }
        return false;
    }

    public SueloAgua getSuelo() {
        return suelo;
    }

    public void setSuelo(SueloAgua suelo) {
        this.suelo = suelo;
    }
    
    
}
