/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.myfarm.frontend;

import com.mycompany.myfarm.frontend.paneles.PanelMenuPrincipal;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import javax.swing.JPanel;

/**
 *
 * @author ronaldo
 */
public class FramePrograma extends javax.swing.JFrame {
    private static final int TAMAÑO_ANCHO=1000;
    private static final int TAMAÑO_ALTO=700;
    /**
     * Creates new form FramePrograma
     */
    public FramePrograma() {
        initComponents();
        setTitle("My Farm");
        ponerPanelEnFramePrincipal(new PanelMenuPrincipal());
        setLocationRelativeTo(null);
        panelPrincipal.setLayout(new GridLayout());

    }
    public static void ponerPanelEnFramePrincipal(JPanel panel){
        panel.setSize(TAMAÑO_ANCHO, TAMAÑO_ALTO);
        panel.setLocation(0, 0);
        panelPrincipal.removeAll();
        panelPrincipal.add(panel, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setLayout(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
