/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.myfarm.frontend.dialogs.partida.parcela;

import com.mycompany.myfarm.backend.MotorJuego;
import com.mycompany.myfarm.backend.granja.Granja;
import com.mycompany.myfarm.backend.granja.Parcela;
import com.mycompany.myfarm.backend.mercado.Mercado;
import com.mycompany.myfarm.backend.suelo.Suelo;
import com.mycompany.myfarm.backend.suelo.SueloGrama;
import com.mycompany.myfarm.frontend.dialogs.AccionExitosaDialog;
import com.mycompany.myfarm.frontend.dialogs.RegistroParcelaDialog;
import com.mycompany.myfarm.frontend.paneles.Partida.Granja.PanelSinAccion;
import java.awt.GridLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author ronaldo
 */
public class CrearParcelaDialgo extends javax.swing.JDialog {
    private Granja granja;
    private boolean empezoSeleccionParcelas;
    
    /**
     * Creates new form CrearParcelaDialgo
     */
    public CrearParcelaDialgo(Granja granja) {
        initComponents();
        this.granja=granja;
        setLocationRelativeTo(null);
        panelSuelos2.setLayout(new GridLayout(granja.getFilas(), granja.getColumnas(), 2, 2));
        cargarSuelosAPanel(granja.getSuelos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelSuelos2 = new javax.swing.JPanel();
        lblEncabezado = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        btnCrearParcela = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(0, 204, 204));
        panelPrincipal.setForeground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout panelSuelos2Layout = new javax.swing.GroupLayout(panelSuelos2);
        panelSuelos2.setLayout(panelSuelos2Layout);
        panelSuelos2Layout.setHorizontalGroup(
            panelSuelos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelSuelos2Layout.setVerticalGroup(
            panelSuelos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        lblEncabezado.setBackground(new java.awt.Color(51, 204, 0));
        lblEncabezado.setFont(new java.awt.Font("Ubuntu Mono", 1, 36)); // NOI18N
        lblEncabezado.setForeground(new java.awt.Color(0, 0, 0));
        lblEncabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEncabezado.setText("CRIAZA");
        lblEncabezado.setOpaque(true);

        lblInfo.setFont(new java.awt.Font("Ubuntu Mono", 0, 19)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(0, 0, 0));
        lblInfo.setText("Seleccion los suelos que formaran parte se la parcela:");

        btnCrearParcela.setBackground(new java.awt.Color(0, 204, 102));
        btnCrearParcela.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        btnCrearParcela.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearParcela.setText("Crear Parcela");
        btnCrearParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearParcelaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(btnCrearParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(lblInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(panelSuelos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(58, 58, 58))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addComponent(lblEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelSuelos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCrearParcela, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearParcelaActionPerformed
        boolean seleccionoBienLasParcelas = granja.seleccionoCeldasCorrectas();
        if (seleccionoBienLasParcelas) {
            Parcela parcela = new Parcela();
            granja.añadirSuelosAParcela(parcela);
            granja.getParcelas().agregarElemento(parcela);
            this.dispose();
            RegistroParcelaDialog dialog = new RegistroParcelaDialog(parcela);
            dialog.setVisible(true);

        } else {
            granja.reiniciarEstadoSuelosGrama();
            JOptionPane.showMessageDialog(this, "No seleccionaste bien las parcelas vuelve a intentarlo", "Error al seleccionar parcela", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearParcelaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        granja.quitarSeleccionadoASuelos();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cargarSuelosAPanel(Suelo[] []suelos){
        for (int i = 0; i < granja.getFilas(); i++) {
            for(int j=0;j<granja.getColumnas(); j++){
                if(suelos[i][j] instanceof SueloGrama){
                    SueloGrama suelo = (SueloGrama) suelos[i][j];
                    panelSuelos2.add(suelo.getPanelDisponibilidad());
                    suelo.getPanelDisponibilidad().inicilizarFondoYLabelInfo();
                    revalidate();
                    repaint();
                }
                else{
                    panelSuelos2.add(new PanelSinAccion());
                }
                revalidate();
                repaint();
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearParcela;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblEncabezado;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuelos;
    private javax.swing.JPanel panelSuelos1;
    private javax.swing.JPanel panelSuelos2;
    // End of variables declaration//GEN-END:variables
}
