/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.myfarm.frontend.dialogs.partida.parcela;

import com.mycompany.myfarm.backend.granja.Bodega;
import com.mycompany.myfarm.backend.granja.Parcela;
import com.mycompany.myfarm.frontend.dialogs.AccionExitosaDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author ronaldo
 */
public class ProduccionAnimalesDialog extends javax.swing.JDialog {
    private Parcela parcela;
    private Bodega bodega;
    /**
     * Creates new form ProduccionAnimalesDialog
     */
    public ProduccionAnimalesDialog(Parcela parcela, Bodega bodega) {
        initComponents();
        setLocationRelativeTo(null);
        this.parcela=parcela;
        this.bodega=bodega;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnProduccionUnoALaVez = new javax.swing.JButton();
        btnPorParcela = new javax.swing.JButton();
        btnParcelaProduccionAlimentos = new javax.swing.JButton();
        btnParcelaProduccionMateriaPrima = new javax.swing.JButton();
        ParcelaProduccionConDestace = new javax.swing.JButton();
        ParcelaProduccionSinDestace = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        panelPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Ubuntu Mono", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECCION DEL TIPO DE PRODUCCION");
        jLabel1.setOpaque(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setOpaque(false);

        btnProduccionUnoALaVez.setText("Un Animal  a la vez");
        btnProduccionUnoALaVez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduccionUnoALaVezActionPerformed(evt);
            }
        });

        btnPorParcela.setText("Por Parcela");
        btnPorParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorParcelaActionPerformed(evt);
            }
        });

        btnParcelaProduccionAlimentos.setText("Por Parcela Y Produccion de Alimentos");
        btnParcelaProduccionAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParcelaProduccionAlimentosActionPerformed(evt);
            }
        });

        btnParcelaProduccionMateriaPrima.setText("Por Parcela Y Produccion de Materia Prima");
        btnParcelaProduccionMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParcelaProduccionMateriaPrimaActionPerformed(evt);
            }
        });

        ParcelaProduccionConDestace.setText("Por Parcela Con destace");
        ParcelaProduccionConDestace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParcelaProduccionConDestaceActionPerformed(evt);
            }
        });

        ParcelaProduccionSinDestace.setText("Por Parcela Sin destace");
        ParcelaProduccionSinDestace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParcelaProduccionSinDestaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnParcelaProduccionMateriaPrima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnParcelaProduccionAlimentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPorParcela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProduccionUnoALaVez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ParcelaProduccionConDestace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ParcelaProduccionSinDestace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnProduccionUnoALaVez, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnParcelaProduccionAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnParcelaProduccionMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ParcelaProduccionConDestace, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ParcelaProduccionSinDestace, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProduccionUnoALaVezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduccionUnoALaVezActionPerformed
        ProduccionUnoALaVezDialog dialog = new ProduccionUnoALaVezDialog(parcela, bodega);
        dialog.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProduccionUnoALaVezActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnPorParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorParcelaActionPerformed
        if (parcela.hayAnimalesVivos()) {
            String listaProductos = parcela.hacerListaProductos();
            parcela.procesarParcela(bodega);
            AccionExitosaDialog dialog = new AccionExitosaDialog("Se procesaron: " + listaProductos);
            dialog.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "No hay animales vivos por procesar", "Sin animales vivos", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnPorParcelaActionPerformed

    private void btnParcelaProduccionAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParcelaProduccionAlimentosActionPerformed
        if (parcela.elAnimalGeneraAlimentos()) {
            String listaProductos = parcela.hacerListaAlimentos();
            parcela.procesarParcelaProduccionAlimento(bodega);
            AccionExitosaDialog dialog = new AccionExitosaDialog("Se procesaron: " + listaProductos);
            dialog.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Los animales de esta parcela no generan Alimentos", "Sin Alimentos", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnParcelaProduccionAlimentosActionPerformed

    private void btnParcelaProduccionMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParcelaProduccionMateriaPrimaActionPerformed
        if (parcela.elAnimalGeneraMateriaPrima()) {
            String listaProductos = parcela.hacerListaMateriaPrima();
            parcela.procesarParcelaProduccionMateriaPrima(bodega);
            AccionExitosaDialog dialog = new AccionExitosaDialog("Se procesaron: " + listaProductos);
            dialog.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this,"Los animales de esta parcela no generan materia prima", "Sin materia prima", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnParcelaProduccionMateriaPrimaActionPerformed

    private void ParcelaProduccionConDestaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParcelaProduccionConDestaceActionPerformed
        if (parcela.elAnimalGeneraProductosConDestace()) {
            String listaProductos = parcela.hacerListaProductosConDestace();
            parcela.procesarParcelaProduccionConDestace(bodega);
            parcela.actualizarIconoParcela(5);
            AccionExitosaDialog dialog = new AccionExitosaDialog("Se procesaron: " + listaProductos);
            dialog.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Los animales de esta parcela no generan alimentos al ser destazados", "Sin productos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ParcelaProduccionConDestaceActionPerformed

    private void ParcelaProduccionSinDestaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParcelaProduccionSinDestaceActionPerformed
        if (parcela.elAnimalGeneraProductosSinDestace()) {
            String listaProductos = parcela.hacerListaProductosSinDestace();
            parcela.procesarParcelaProduccionSinDestace(bodega);
            AccionExitosaDialog dialog = new AccionExitosaDialog("Se procesaron: " + listaProductos);
            dialog.setVisible(true);
            this.dispose();
        }
                else{
            JOptionPane.showMessageDialog(this,"Los animales de esta parcela no generan productos sin ser destazados", "Sin Productos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ParcelaProduccionSinDestaceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ParcelaProduccionConDestace;
    private javax.swing.JButton ParcelaProduccionSinDestace;
    private javax.swing.JButton btnParcelaProduccionAlimentos;
    private javax.swing.JButton btnParcelaProduccionMateriaPrima;
    private javax.swing.JButton btnPorParcela;
    private javax.swing.JButton btnProduccionUnoALaVez;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
