/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.myfarm.frontend.dialogs.partida.parcela;

import com.mycompany.myfarm.backend.granja.Granja;
import com.mycompany.myfarm.backend.granja.Parcela;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ronaldo
 */
public class VerParcelasDialog extends javax.swing.JDialog {
        private Granja granja;
    /**
     * Creates new form VerParcelasDialog
     */
    public VerParcelasDialog(Granja granja) {
        initComponents();
        this.granja=granja;
        setLocationRelativeTo(null);
        cargarTablaYCmbBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaParcelas = new javax.swing.JTable();
        cmbIndiceParcela = new javax.swing.JComboBox<>();
        btnSiguiente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbAcciones = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        panelPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Ubuntu Mono", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECCION DE PARCELAS");
        jLabel1.setOpaque(true);

        tablaParcelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Nombre", "Espacio"
            }
        ));
        jScrollPane1.setViewportView(tablaParcelas);

        cmbIndiceParcela.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Selecciona una parcela,selecciona una accion y presiona siguiente");

        cmbAcciones.setFont(new java.awt.Font("Ubuntu Mono", 1, 22)); // NOI18N
        cmbAcciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentar", "Producir", "Limpiar", "Quitar" }));
        cmbAcciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAccionesActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbAcciones, 0, 176, Short.MAX_VALUE)
                            .addComponent(cmbIndiceParcela, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbIndiceParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        int indice = cmbIndiceParcela.getSelectedIndex();
        int accion = cmbAcciones.getSelectedIndex();
        Parcela parcela = granja.getParcelas().obtenerContenido(indice);

        switch (accion) {
            case 0: 
                if (!parcela.getAnimales().esVacia() && parcela.hayAnimalesVivos()) {
                    AlimentarAnimalesDialog dialog = new AlimentarAnimalesDialog(parcela, granja);
                    dialog.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No hay animales vivos en esta parcela", "Sin animales", JOptionPane.ERROR_MESSAGE);
                }
                break;

            case 1: 
                if (!parcela.getAnimales().esVacia() && parcela.hayAnimalesVivos()) {
                    ProduccionAnimalesDialog dialog = new ProduccionAnimalesDialog(parcela, granja.getBodega());
                    dialog.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No hay animales vivos en esta parcela", "Sin animales", JOptionPane.ERROR_MESSAGE);
                }
                break;

            case 2: 
                if (!parcela.getAnimales().esVacia() && parcela.contarAnimalesMuertos() > 0) {
                    LimpiezaParcelaDialog dialog = new LimpiezaParcelaDialog(parcela, granja.getGranjero());
                    dialog.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No hay animales muertos en esta parcela", "Sin animales muertos", JOptionPane.ERROR_MESSAGE);
                }
                break;

            case 3: 
                if (parcela.getAnimales().esVacia()) {
                    PagarEliminacionParcelaDialog dialog = new PagarEliminacionParcelaDialog(granja, indice);
                    dialog.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No se puede eliminar una parcela con animales dentro", "Parcela ocupada", JOptionPane.ERROR_MESSAGE);
                }
                break;

            default:
                
                break;
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cmbAccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAccionesActionPerformed

    public void cargarTablaYCmbBox() {
        DefaultTableModel modelo = (DefaultTableModel) tablaParcelas.getModel();
        for (int i = 0; i < granja.getParcelas().getTamaño(); i++) {
            modelo.addRow(new Object[]{(i + 1), granja.getParcelas().obtenerContenido(i).getNombre(), granja.getParcelas().obtenerContenido(i).getSuelos().getTamaño()});
            cmbIndiceParcela.addItem("" + (i + 1));
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> cmbAcciones;
    private javax.swing.JComboBox<String> cmbIndiceParcela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tablaParcelas;
    // End of variables declaration//GEN-END:variables
}
